// AUTO-GENERATED by apps/video-studio/scripts/generate-captions.mjs — do not
// edit by hand. Re-run that script after changing narration.json or
// re-timing any BSL clip's trimStartSeconds.
export type DemoCaptionCue = {
  start: number;
  end: number;
  text: string;
};

export const bslCaptionsEn: DemoCaptionCue[] = [
  {
    "start": 3.5,
    "end": 11.69,
    "text": "Blockchain Summit Latam brings the region's Web3 builders and investors together — claim your pass and step right into the event."
  },
  {
    "start": 13.98,
    "end": 20.98,
    "text": "Browse the full agenda in seconds — every talk, every stage, every speaker on tour, all in one place."
  },
  {
    "start": 24.38,
    "end": 26.76,
    "text": "Found someone you want to meet?"
  },
  {
    "start": 26.71,
    "end": 34.19,
    "text": "Send a meeting request in a tap, add a quick note on why, and lock in your one-on-one before the event even starts."
  }
];

export const bslCaptionsEs: DemoCaptionCue[] = [
  {
    "start": 3.5,
    "end": 11.31,
    "text": "Blockchain Summit Latam reúne a los constructores e inversionistas de Web3 de la región — reclama tu pase y entra directo al evento."
  },
  {
    "start": 13.98,
    "end": 22.01,
    "text": "Explora la agenda completa en segundos: cada charla, cada escenario, cada ponente de la gira, todo en un solo lugar."
  },
  {
    "start": 24.38,
    "end": 27.73,
    "text": "Encontraste a alguien con quien quieres reunirte?"
  },
  {
    "start": 27.68,
    "end": 36.32,
    "text": "Envía una solicitud de reunión con un toque, añade una nota breve sobre el motivo, y asegura tu cita uno a uno antes de que comience el evento."
  }
];
