// AUTO-GENERATED by apps/video-studio/scripts/generate-captions.mjs — do not
// edit by hand. Re-run that script after changing narration.json or
// re-timing any clip's trimStartSeconds.
export type DemoCaptionCue = {
  start: number;
  end: number;
  text: string;
};

export const demoCaptionsEn: DemoCaptionCue[] = [
  {
    "start": 3.5,
    "end": 7.46,
    "text": "Welcome to Hash Pass — your digital event platform."
  },
  {
    "start": 7.41,
    "end": 13.35,
    "text": "Discover events, connect with your community, and manage your passes, all in one place."
  },
  {
    "start": 15.22,
    "end": 17.52,
    "text": "Getting started is easy."
  },
  {
    "start": 17.47,
    "end": 23.58,
    "text": "Sign in instantly with a one-time code by email, or continue with Google in a single tap."
  },
  {
    "start": 23.74,
    "end": 32.4,
    "text": "Once you're in, your dashboard puts everything front and center — explore every event on the Hash Pass network and jump straight into your passes."
  },
  {
    "start": 37.34,
    "end": 40.24,
    "text": "Keep your attendee profile up to date."
  },
  {
    "start": 40.19,
    "end": 45.45,
    "text": "Add your role and company so organizers and speakers know exactly who they're meeting."
  },
  {
    "start": 46.22,
    "end": 56.71,
    "text": "Switch between every event on the tour in a tap — Chile, Colombia, Peru, and more — each with its own agenda, speakers, and quick access to everything you need."
  },
  {
    "start": 61.78,
    "end": 65.04,
    "text": "And you can carry Hash Pass with you everywhere."
  },
  {
    "start": 64.99,
    "end": 72.71,
    "text": "Install it straight from your browser to launch it like a native app from your home screen, or find Hash Pass on the Google Play Store."
  }
];

export const demoCaptionsEs: DemoCaptionCue[] = [
  {
    "start": 3.5,
    "end": 7.75,
    "text": "Bienvenido a Hash Pass, tu plataforma digital de eventos."
  },
  {
    "start": 7.7,
    "end": 13.68,
    "text": "Descubre eventos, conecta con tu comunidad y gestiona tus pases, todo en un solo lugar."
  },
  {
    "start": 17.74,
    "end": 20.05,
    "text": "Empezar es muy fácil."
  },
  {
    "start": 20,
    "end": 25.54,
    "text": "Inicia sesión al instante con un código por correo, o continúa con Google con un toque."
  },
  {
    "start": 26.7,
    "end": 35,
    "text": "Una vez dentro, tu panel lo pone todo al alcance de la mano: explora cada evento en la red de Hash Pass y accede directo a tus pases."
  },
  {
    "start": 40.26,
    "end": 43.43,
    "text": "Mantén actualizado tu perfil de asistente."
  },
  {
    "start": 43.39,
    "end": 48.87,
    "text": "Añade tu cargo y empresa para que organizadores y ponentes sepan con quién se reúnen."
  },
  {
    "start": 49.3,
    "end": 59.65,
    "text": "Cambia entre cada evento de la gira con un toque: Chile, Colombia, Perú y más, cada uno con su propia agenda, ponentes y acceso rápido a todo lo que necesitas."
  },
  {
    "start": 65.62,
    "end": 69.32,
    "text": "Y puedes llevar Hash Pass contigo a todas partes."
  },
  {
    "start": 69.27,
    "end": 76.71,
    "text": "Instálala directamente desde tu navegador para abrirla como una app nativa desde tu pantalla de inicio, o búscala en Google Play."
  }
];
