import React from 'react';
import { Platform, Text } from 'react-native';
import {
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BellOff,
  Bot,
  BookOpen,
  Building2,
  Cog,
  CalendarDays,
  CalendarX2,
  Camera,
  ChartBar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  CloudDownload,
  Bug,
  Compass,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePause,
  CirclePlay,
  CircleX,
  Eye,
  ExternalLink,
  FilterX,
  Fingerprint,
  Globe,
  History,
  Hourglass,
  IdCard,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  Link2,
  Lock,
  LockOpen,
  Mail,
  MailOpen,
  MailPlus,
  MapPin,
  Maximize,
  Menu,
  MessageCircle,
  Moon,
  Lightbulb,
  PartyPopper,
  Phone,
  Plus,
  QrCode,
  Ticket,
  RefreshCw,
  RotateCw,
  ScanQrCode,
  Search,
  SearchX,
  Send,
  Share2,
  Shield,
  ShieldCheck,
  LogIn,
  LogOut,
  SquarePlay,
  Star,
  SlidersHorizontal,
  Tag,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  Users,
  UsersRound,
  Video,
  VolumeX,
  Wallet,
  X,
  Zap,
  type LucideProps,
} from 'lucide-react-native';
import type { TextStyle } from 'react-native';
// Use a relative node_modules path so the Babel module-resolver alias for
// `@expo/vector-icons` does not rewrite these native fallbacks back into this wrapper.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const NativeIonicons = require('../../../node_modules/@expo/vector-icons/Ionicons.js').default as React.ComponentType<LucideProps>;
// eslint-disable-next-line @typescript-eslint/no-require-imports
const NativeMaterialIcons = require('../../../node_modules/@expo/vector-icons/MaterialIcons.js').default as React.ComponentType<LucideProps>;

type IconProps = { name: string; size?: number; color?: string; style?: any };

type WebIconComponent = React.ComponentType<LucideProps>;

function GoogleIcon({ size = 24, color = '#4285F4', style }: { size?: number; color?: string; style?: TextStyle }) {
  return (
    <Text
      style={[
        {
          width: size,
          height: size,
          lineHeight: size,
          fontSize: size * 0.82,
          fontWeight: '700',
          textAlign: 'center',
          textAlignVertical: 'center',
          color,
          fontFamily: 'Arial',
          includeFontPadding: false,
        },
        style,
      ]}
    >
      G
    </Text>
  );
}

const WEB_MATERIAL_ICONS: Record<string, WebIconComponent> = {
  add: Plus,
  analytics: ChartBar,
  'arrow-back': ArrowLeft,
  'arrow-downward': ArrowDown,
  'arrow-forward': ArrowRight,
  'arrow-upward': ArrowUp,
  assignment: ClipboardList,
  block: X,
  bolt: Zap,
  'book-outline': BookOpen,
  book: BookOpen,
  'bug-report': Bug,
  business: Building2,
  'camera-alt': Camera,
  'camera-outline': Camera,
  cancel: CircleX,
  'card-membership': IdCard,
  celebration: PartyPopper,
  chat: MessageCircle,
  check: Check,
  'check-circle': CircleCheck,
  'checkmark-circle': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'clear-all': FilterX,
  clear: X,
  close: X,
  'close-circle': CircleX,
  'cloud-download': CloudDownload,
  'cloud-download-outline': CloudDownload,
  'confirmation-number': Ticket,
  dashboard: LayoutDashboard,
  drafts: MailOpen,
  email: Mail,
  'error-outline': CircleAlert,
  event: CalendarDays,
  'event-busy': CalendarX2,
  explore: Compass,
  favorite: Star,
  'filter-list': SlidersHorizontal,
  'flash-on': Zap,
  flip: RotateCw,
  'help-outline': CircleHelp,
  history: History,
  'hourglass-empty': Hourglass,
  inbox: Inbox,
  info: Info,
  'info-outline': Info,
  'call': Phone,
  'keyboard-arrow-down': ChevronDown,
  'calendar-today': CalendarDays,
  key: KeyRound,
  dialpad: KeyRound,
  label: Tag,
  language: Globe,
  link: Link2,
  'link-outline': Link2,
  'location-on': MapPin,
  'lock-open': LockOpen,
  'log-in': LogIn,
  'log-out-outline': LogOut,
  login: LogIn,
  logout: LogOut,
  'mark-email-unread': MailPlus,
  menu: Menu,
  moon: Moon,
  'moon-outline': Moon,
  notifications: Bell,
  'notifications-none': BellOff,
  'open-in-full': Maximize,
  'open-in-new': ExternalLink,
  lightbulb: Lightbulb,
  'lightbulb-outline': Lightbulb,
  'pause-circle-outline': CirclePause,
  people: Users,
  'people-alt': UsersRound,
  'eye-outline': Eye,
  'eye': Eye,
  'finger-print-outline': Fingerprint,
  'lock-closed-outline': Lock,
  'people-outline': Users,
  person: User,
  'person-outline': User,
  'account-circle': User,
  'emoji-emotions': PartyPopper,
  android: Bot,
  face: User,
  'photo-camera': Camera,
  'trash-outline': Trash2,
  'play-circle-outline': CirclePlay,
  'qr-code': QrCode,
  'qr-code-outline': QrCode,
  'qr-code-scanner': ScanQrCode,
  refresh: RefreshCw,
  'search-off': SearchX,
  'search-outline': Search,
  send: Send,
  share: Share2,
  'shield-checkmark': ShieldCheck,
  'shield-outline': Shield,
  security: Shield,
  star: Star,
  'ticket-outline': Ticket,
  'warning-outline': TriangleAlert,
  sunny: Sun,
  'wb-sunny': Sun,
  sync: RefreshCw,
  tune: SlidersHorizontal,
  'video-call': Video,
  'volume-off': VolumeX,
  warning: TriangleAlert,
  settings: Cog,
  'call-outline': Phone,
  'logo-google-playstore': SquarePlay,
  'logo-apple': Apple,
  wallet: Wallet,
};

function WebMaterialIcons({ name, ...props }: IconProps) {
  const MappedIcon = WEB_MATERIAL_ICONS[name] ?? CircleHelp;
  return <MappedIcon {...props} />;
}

function WebIonicons({ name, ...props }: IconProps) {
  if (name === 'logo-google') {
    return <GoogleIcon {...props} />;
  }

  if (name === 'logo-google-playstore') {
    return <SquarePlay {...props} />;
  }

  if (name === 'logo-apple') {
    return <Apple {...props} />;
  }

  const mappedName = WEB_IONICONS_TO_MATERIAL_ICONS[name] ?? 'help-outline';
  return <WebMaterialIcons {...props} name={mappedName} />;
}

// Keep web rendering off the Expo font path so the browser never requests TTF assets.
const WEB_IONICONS_TO_MATERIAL_ICONS: Record<string, string> = {
  'alert-circle': 'error-outline',
  'alert-circle-outline': 'error-outline',
  'arrow-back': 'arrow-back',
  'arrow-up': 'arrow-upward',
  'book-outline': 'book',
  'calendar-outline': 'calendar-today',
  'call-outline': 'call',
  'camera-outline': 'camera-alt',
  'checkmark-circle': 'check-circle',
  'chevron-down': 'keyboard-arrow-down',
  'chevron-forward': 'chevron-right',
  close: 'close',
  'close-circle': 'cancel',
  'cloud-download-outline': 'cloud-download',
  'calendar-today': 'calendar-today',
  'compass-outline': 'explore',
  dialpad: 'dialpad',
  'information-circle-outline': 'info-outline',
  'keypad-outline': 'dialpad',
  'link-outline': 'link',
  'log-in': 'login',
  'log-out-outline': 'logout',
  'mail-open-outline': 'drafts',
  'mail-outline': 'email',
  menu: 'menu',
  moon: 'moon',
  'moon-outline': 'moon',
  'document-text-outline': 'assignment',
  'eye-outline': 'eye-outline',
  'finger-print-outline': 'finger-print-outline',
  'globe-outline': 'language',
  'help-circle-outline': 'help-outline',
  'language-outline': 'language',
  'lock-closed-outline': 'lock-closed-outline',
  'notifications-outline': 'notifications',
  'people-outline': 'people-outline',
  'person-outline': 'person',
  'refresh-outline': 'refresh',
  'school-outline': 'book-outline',
  'trash-outline': 'trash-outline',
  'qr-code-outline': 'qr-code',
  refresh: 'refresh',
  'search-outline': 'search',
  'settings-outline': 'settings',
  'shield-outline': 'security',
  'shield-checkmark-outline': 'shield-checkmark',
  star: 'star',
  'ticket-outline': 'confirmation-number',
  'wallet-outline': 'wallet',
  'warning-outline': 'warning',
  sunny: 'sunny',
  'logo-apple': 'logo-apple',
  'logo-google-playstore': 'logo-google-playstore',
};

export const Ionicons = Platform.OS === 'web' ? WebIonicons : NativeIonicons;
export const MaterialIcons = Platform.OS === 'web' ? WebMaterialIcons : NativeMaterialIcons;
