functionsDirectory = "/home/ed/Documents/hash/hashpass.tech/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/home/ed/Documents/hash/hashpass.tech/dist/client"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:web"
functions = "/home/ed/Documents/hash/hashpass.tech/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["dist/server/**/*"]

[[headers]]
for = "/dist/server/_expo/functions/*"

[headers.values]
Cache-Control = "public, max-age=60, s-maxage=60"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]