version: 0.2

env:
  shell: bash
  variables:
    PNPM_STORE_DIR: .pnpm-store

phases:
  build:
    commands:
      - bash packages/tools/scripts/build-static-site.sh
      - bash packages/tools/scripts/deploy-static-site.sh

artifacts:
  base-directory: dist/client
  files:
    - '**/*'
