packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - argon2
  - aws-sdk
  - bufferutil
  - chromedriver
  - core-js
  - esbuild
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver
  - utf-8-validate
