packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - argon2
  - aws-sdk
  - bufferutil
  - chromedriver
  - core-js
  - esbuild
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver
  - utf-8-validate
allowBuilds:
  argon2: true
  aws-sdk: true
  bufferutil: true
  chromedriver: true
  core-js: true
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
