import type {
  AgendaItem,
  EventConfig,
  EventContinent,
  Speaker,
} from "@hashpass/types";
import { getHashPokerEventConfig } from "./ingested-event-config";

export type {
  Speaker,
  AgendaItem,
  EventConfig,
  EventContinent,
} from "@hashpass/types";

const BSL_API_BASE_PATH = "/api/bsl";
// Speaker photos are hosted on our own S3 bucket (target AWS account), not
// scraped/hotlinked from blockchainsummit.la at runtime -- see
// hashpass-production-event-media-952191196420-us-east-2/events/chile2026/speakers/.
const CHILE2026_SPEAKER_IMAGE_BASE =
  "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/chile2026/speakers";
const CBWEEK2026_SPEAKER_IMAGE_BASE =
  "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/cbweek2026/speakers";
const EVENT_MEDIA_BASE =
  "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events";
const eventHeroAssetVersion = (eventId: string): string =>
  eventId === "hash-poker" ? "v4" : "v3";
const eventHeroVideo = (eventId: string): string =>
  `${EVENT_MEDIA_BASE}/${eventId}/branding/hashpass-event-hero-${eventHeroAssetVersion(eventId)}.mp4`;
const eventHeroPoster = (eventId: string): string =>
  `${EVENT_MEDIA_BASE}/${eventId}/branding/hashpass-event-hero-${eventHeroAssetVersion(eventId)}.jpg`;

// CBWeek has not announced its 2026 speakers. These are the people explicitly
// listed by CBWeek as speakers from past editions; keeping them in the
// directory as references gives the demo real portraits without representing
// them as confirmed for the 2026 event.
const CBWEEK2026_PAST_EDITION_SPEAKERS: Speaker[] = [
  ['4abf6fc1-98a6-4c13-9b9f-100000000001', 'Charles Hoskinson', 'Founder Cardano Blockchain', 'CARDANO', 'charles-hoskinson'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000002', 'Hernando de Soto', 'Presidente', 'ILD', 'hernando-de-soto'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000003', 'Hong Fang', 'Presidente de OKX', 'OKX', 'hong-fang'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000004', 'Daniel Acosta', 'Head of LATAM', 'BINANCE', 'daniel-acosta'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000005', 'Patricio Mesri', 'Latam Country Manager', 'BYBIT', 'patricio-mesri'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000006', 'Salvador Rivero', 'General Manager México', 'BINANCE', 'salvador-rivero'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000007', 'Carolina Gama', 'Country Manager & LATAM Marketing Head', 'BITGET', 'carolina-gama'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000008', 'Javier Gamboa', 'Business Developer Manager', 'BITUNIX', 'javier-gamboa'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000009', 'André Sprone', 'Head of Latam', 'MEXC', 'andre-sprone'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000010', 'Lesme Hernández', 'Brand Manager LATAM', 'BINGX', 'lesme-hernandez'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000011', 'Santiago Juarros', 'Sr. Manager & Partner Marketing', 'CIRCLE', 'santiago-juarros'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000012', 'Drey Dias', 'Sales Director', 'CHAINALYSIS', 'drey-dias'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000013', 'Valentino Ruiz', 'Institutional Sales Trader', 'BLOCKCHAIN.COM', 'valentino-ruiz'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000014', 'Lucas Macchiavelli', 'Operaciones Comerciales Global', 'INPUT OUTPUT', 'lucas-macchiavelli'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000015', 'Mauro Andreoli', 'Midnight & IOG Argentina Representative', 'MIDNIGHT', 'mauro-andreoli'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000016', 'Francisco Carvalho', 'CEO & Founder', 'BLOCKCHAIN RIO', 'francisco-carvalho'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000017', 'Andre Gejde', 'Regional Growth Manager', 'TANGEM', 'andre-gejde'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000018', 'Amilcar Erazo', 'Co-Founder & CEO', 'MERU', 'amilcar-erazo'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000019', 'Rubén Galindo Steckel', 'CEO', 'AIRTM', 'ruben-galindo-steckel'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000020', 'Rodrigo Martinez', 'Regional Manager LATAM', 'VANTAGE', 'rodrigo-martinez'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000021', 'Renato Palacios', 'Business Developer', 'EXNESS', 'renato-palacios'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000022', 'Efraín Barraza', 'Regional Expansion Manager LATAM', 'TETHER', 'efrain-barraza'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000023', 'Patrick O’Neill', 'Founder & Managing Partner', 'SHERLOCK COMMUNICATIONS', 'patrick-oneill'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000024', 'Alvaro Olivares', 'Country Manager', 'BITGO', 'alvaro-olivares'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000025', 'Pablo De Santis', 'Communications Lead South Cone', 'WORLD', 'pablo-de-santis'],
  ['4abf6fc1-98a6-4c13-9b9f-100000000026', 'Valentín Popescu', 'Co-Founder & Director', 'MOTIV PERÚ', 'valentin-popescu'],
].map(([id, name, title, company, imageSlug]) => ({
  id,
  name,
  title,
  company,
  bio: `Official CBWeek past-edition speaker reference. ${name} is not announced as a CBWeek 2026 speaker.`,
  image: `${CBWEEK2026_SPEAKER_IMAGE_BASE}/past-editions/${imageSlug}.webp`,
  isActive: false,
  isPastEditionReference: true,
}));
const BSL_DATABASE = {
  schema: "bsl",
  tables: {
    speakers: "bsl_speakers",
    bookings: "bsl_bookings",
    attendees: "bsl_attendees",
  },
} as const;

const BSL_SHARED_API_ENDPOINTS = {
  speakers: "speakers",
  bookings: "bookings",
  "verify-ticket": "verify-ticket",
  "auto-match": "auto-match",
  agenda: "agenda",
  status: "status",
} as const;

const BSL_HUB_BRANDING = {
  primaryColor: "#00A9E0",
  secondaryColor: "#06111F",
  logo: "/assets/logos/bsl/bsl-ontour-pro.svg",
  favicon: "/favicon.ico",
} as const;

const BSL_TOUR_SHARED_FEATURES = [
  "matchmaking",
  "speakers",
  "bookings",
  "admin",
] as const;

const makeTourQuickAccess = (eventId: string) =>
  [
    {
      id: "agenda",
      title: "Event Agenda",
      subtitle: "Schedule",
      icon: "event",
      color: "#34A853",
      route: `/events/${eventId}/agenda`,
    },
    {
      id: "networking",
      title: "Networking Center",
      subtitle: "Connect & meet",
      icon: "people-alt",
      color: "#4CAF50",
      route: `/events/${eventId}/networking`,
    },
    {
      id: "speakers",
      title: "Featured Speakers",
      subtitle: "Meet the experts",
      icon: "people",
      color: "#007AFF",
      route: `/events/${eventId}/speakers/calendar`,
    },
    {
      id: "event-info",
      title: "Event Information",
      subtitle: "Details & Logistics",
      icon: "info",
      color: "#FF9500",
      route: `/events/${eventId}/event-info`,
    },
  ] as const;

const makeTourHubQuickAccess = () =>
  [
    {
      id: "peru2026",
      title: "Peru 2026",
      subtitle: "Lima • May 13-15",
      icon: "location-on",
      color: "#D11A2A",
      route: "/events/peru2026/home",
    },
    {
      id: "chile2026",
      title: "Chile 2026",
      subtitle: "Santiago • Aug 5-7",
      icon: "location-on",
      color: "#FF5B5B",
      route: "/events/chile2026/home",
    },
    {
      id: "colombia2026",
      title: "Colombia 2026",
      subtitle: "Bogotá • Nov 4-6",
      icon: "location-on",
      color: "#F5C542",
      route: "/events/colombia2026/home",
    },
    {
      id: "bsl2025",
      title: "BSL 2025 Archive",
      subtitle: "Medellín • Legacy edition",
      icon: "history",
      color: "#60A5FA",
      route: "/events/bsl2025/home",
    },
  ] as const;

const makeTourStopConfig = (
  eventId: "peru2026" | "chile2026" | "colombia2026",
  options: {
    name: string;
    title: string;
    subtitle: string;
    aliases?: string[];
    color: string;
    eventStartDate: string;
    eventEndDate: string;
    eventDateString: string;
    city: string;
    country: string;
    continent: EventContinent;
    venue: string;
    summary: string;
    stopOrder: number;
    image: string;
    brandingLogo: string;
    heroVideo?: string;
    heroPoster?: string;
    speakers: Speaker[];
    agenda: AgendaItem[];
    dayThemes?: Record<string, { es: string; en: string }>;
    speakerApplicationUrl?: string;
  },
): EventConfig => ({
  id: eventId,
  name: options.name,
  aliases: options.aliases,
  domain: `${eventId}.hashpass.tech`,
  website: `https://blockchainsummit.la/${eventId}/`,
  title: options.title,
  subtitle: options.subtitle,
  image: options.image,
  heroVideo: options.heroVideo || eventHeroVideo(eventId),
  heroPoster: options.heroPoster || eventHeroPoster(eventId),
  color: options.color,
  eventStartDate: options.eventStartDate,
  eventEndDate: options.eventEndDate,
  eventDateString: options.eventDateString,
  series: "Summit",
  geo: {
    country: options.country,
    continent: options.continent,
  },
  features: [...BSL_TOUR_SHARED_FEATURES],
  eventType: "whitelabel",
  authAllyIds: ["hash-poker-room", "bsl"],
  branding: {
    primaryColor: options.color,
    secondaryColor: "#06111F",
    logo: options.brandingLogo,
    favicon: "/favicon.ico",
  },
  api: {
    basePath: BSL_API_BASE_PATH,
    endpoints: { ...BSL_SHARED_API_ENDPOINTS },
  },
  routes: {
    home: `/events/${eventId}/home`,
    speakers: `/events/${eventId}/speakers`,
    bookings: `/events/${eventId}/my-bookings`,
    admin: `/events/${eventId}/admin`,
  },
  database: BSL_DATABASE,
  speakers: options.speakers,
  agenda: options.agenda,
  dayThemes: options.dayThemes,
  speakerApplicationUrl: options.speakerApplicationUrl,
  tour: {
    hubEventId: "bsl",
    role: "stop",
    stopOrder: options.stopOrder,
    city: options.city,
    country: options.country,
    venue: options.venue,
    summary: options.summary,
  },
  quickAccessItems: makeTourQuickAccess(eventId) as any,
});

const HASH_POKER_EVENT = getHashPokerEventConfig();

export const EVENTS: Record<string, EventConfig> = {
  bsl: {
    id: "bsl",
    name: "Blockchain Summit Latam On Tour",
    shortName: "BSL",
    aliases: [
      "bsl",
      "BSL 2026",
      "BSL On Tour",
      "Blockchain Summit",
      "Blockchain Summit Latam",
      "Blockchain Summit Latam On Tour",
      "#bsl",
      "#bsl2026",
    ],
    domain: "bsl.hashpass.tech",
    website: "https://blockchainsummit.la/",
    title: "BSL On Tour",
    subtitle: "Peru, Chile and Colombia 2026 roadshow",
    image: "/assets/logos/bsl/bsl-ontour-pro.svg",
    heroVideo: eventHeroVideo("bsl"),
    heroPoster: eventHeroPoster("bsl"),
    color: "#00A9E0",
    eventDateString: "BSL On Tour • 2026",
    series: "BSL On Tour",
    geo: {
      country: "Colombia",
      continent: "South America",
    },
    features: ["matchmaking", "speakers", "bookings", "admin", "wallet"],
    eventType: "whitelabel",
    authAllyIds: ["hash-poker-room", "bsl"],
    branding: {
      ...BSL_HUB_BRANDING,
    },
    api: {
      basePath: BSL_API_BASE_PATH,
      endpoints: { ...BSL_SHARED_API_ENDPOINTS },
    },
    routes: {
      home: "/events/bsl/home",
      speakers: "/events/bsl/speakers",
      bookings: "/events/bsl/my-bookings",
      admin: "/events/bsl/admin",
    },
    database: {
      schema: "bsl",
      tables: {
        speakers: "bsl_speakers",
        bookings: "bsl_bookings",
        attendees: "bsl_attendees",
        wallets: "wallet_auth",
      },
    },
    tour: {
      hubEventId: "bsl",
      role: "hub",
      summary: "Institutional roadshow across Peru, Chile and Colombia",
    },
    quickAccessItems: makeTourHubQuickAccess() as any,
  },
  peru2026: makeTourStopConfig("peru2026", {
    name: "BSL Perú 2026",
    title: "Blockchain Summit Latam Perú 2026",
    subtitle: "Universidad del Pacífico, Lima",
    color: "#D11A2A",
    eventStartDate: "2026-05-13T09:00:00-05:00",
    eventEndDate: "2026-05-15T23:59:59-05:00",
    eventDateString: "May 13-15, 2026 • Lima, Perú",
    city: "Lima",
    country: "Peru",
    continent: "South America",
    venue: "Universidad del Pacífico",
    summary: "Banco Central de Reserva del Perú and institutional finance.",
    stopOrder: 1,
    image: "/assets/logos/bsl/bsl-peru-pro.svg",
    brandingLogo: "/assets/logos/bsl/bsl-peru-pro.svg",
    speakers: [
      {
        id: "paul-castillo",
        name: "Paul Castillo",
        title: "Gerente General",
        company: "Banco Central de Reserva del Perú",
      },
      {
        id: "elmer-sanchez",
        name: "Elmer Sánchez",
        title: "Gerencia de Operaciones Monetarias y Estabilidad Financiera",
        company: "Banco Central de Reserva del Perú",
      },
      {
        id: "milton-vega",
        name: "Milton Vega",
        title: "Deputy Manager Payments and Financial Infraestructures",
        company: "Central Bank Peru",
      },
      {
        id: "vanesa-colonia",
        name: "Vanesa Colonia",
        title: "Coordinadora de Evaluación",
        company: "UIF Perú / SBS / AFP",
      },
      {
        id: "judith-vergara",
        name: "Judith Vergara",
        title: "Director of Executive Education",
        company:
          "School of Finance, Economics and Government @ Universidad EAFIT",
      },
      {
        id: "magdalena-mahia",
        name: "Magdalena Mahia",
        title: "Team Lead Regulatory & Risk Compliance",
        company: "Lemon",
      },
      {
        id: "erick-ortiz",
        name: "Erick Ortiz",
        title: "Blockchain Advisor / Project Manager Digital Payments",
        company: "BBVA Perú",
      },
      {
        id: "juan-jose-miranda",
        name: "Juan José Miranda",
        title: "Director Innovation Center IC Blockchain/DLT/web3 & QC",
        company: "IBIOL NTT DATA",
      },
      {
        id: "alexandre-borelli",
        name: "Alexandre Borelli",
        title: "CEO Latin America",
        company: "Alcazar Group",
      },
      {
        id: "daniel-garcia",
        name: "Daniel García",
        title:
          "Superintendente Adjunto de Investigación, Desarrollo e Innovación",
        company: "SMV",
      },
      {
        id: "jaime-varela",
        name: "Jaime Varela",
        title: "Growth Manager Latam",
        company: "Binance",
      },
      {
        id: "alireza-siadat",
        name: "Alireza Siadat",
        title: "Head of Strategy and Policy",
        company: "1inch",
      },
      {
        id: "fabiana-alvarado",
        name: "Fabiana Alvarado",
        title: "Asociada Senior",
        company: "Damma Legal Advisors",
      },
      {
        id: "omar-castelblanco",
        name: "Omar Castelblanco",
        title: "Co Founder & CEO",
        company: "Relámpago Payments",
      },
    ],
    agenda: [
      {
        id: "peru-day1-reg",
        day: "1",
        time: "08:00 - 09:00",
        title: "Registro y café de bienvenida",
        type: "registration",
      },
      {
        id: "peru-day1-open",
        day: "1",
        time: "09:00 - 09:15",
        title: "Palabras de apertura BSL Lima",
        type: "keynote",
        speakers: ["paul-castillo"],
      },
      {
        id: "peru-day1-keynote",
        day: "1",
        time: "09:20 - 09:50",
        title:
          "Infraestructura financiera y crecimiento de pagos digitales en Perú",
        type: "keynote",
        speakers: ["paul-castillo", "milton-vega"],
      },
      {
        id: "peru-day1-panel",
        day: "1",
        time: "10:00 - 10:45",
        title: "Panel: regulación, banca central y open finance",
        type: "panel",
        speakers: ["elmer-sanchez", "vanesa-colonia", "judith-vergara"],
      },
      {
        id: "peru-day1-commercial",
        day: "1",
        time: "11:00 - 11:45",
        title:
          "Panel: transformación digital de la banca comercial y mercados financieros",
        type: "panel",
        speakers: ["magdalena-mahia", "erick-ortiz", "alexandre-borelli"],
      },
      {
        id: "peru-day1-lunch",
        day: "1",
        time: "12:00 - 13:30",
        title: "Almuerzo libre y networking estratégico",
        type: "meal",
      },
      {
        id: "peru-day2-assets",
        day: "2",
        time: "14:00 - 14:45",
        title: "Activos digitales institucionales y mercados regulados",
        type: "keynote",
        speakers: ["juan-jose-miranda", "daniel-garcia"],
      },
      {
        id: "peru-day2-compliance",
        day: "2",
        time: "15:00 - 15:45",
        title: "Panel: compliance, custodia y expansión regional",
        type: "panel",
        speakers: ["jaime-varela", "alireza-siadat", "judith-vergara"],
      },
      {
        id: "peru-day3-convergence",
        day: "3",
        time: "16:00 - 16:45",
        title:
          "Mesa de convergencia: infraestructura financiera y adopción institucional",
        type: "panel",
        speakers: ["paul-castillo", "fabiana-alvarado", "omar-castelblanco"],
      },
    ],
  }),
  chile2026: makeTourStopConfig("chile2026", {
    name: "BSL Chile 2026",
    title: "Blockchain Summit Latam Chile 2026",
    subtitle: "Universidad de Chile - FEN, Santiago",
    color: "#FF5B5B",
    eventStartDate: "2026-08-05T09:00:00-04:00",
    eventEndDate: "2026-08-07T23:59:59-04:00",
    eventDateString: "August 5-7, 2026 • Santiago, Chile",
    city: "Santiago",
    country: "Chile",
    continent: "South America",
    venue: "Universidad de Chile - FEN - Alta Dirección",
    summary:
      "Digital finance, payments modernization, and institutional regulation with Banco Central de Chile.",
    stopOrder: 2,
    image: "/assets/logos/bsl/bsl-chile-pro.svg",
    brandingLogo: "/assets/logos/bsl/bsl-chile-pro.svg",
    // Verified against https://blockchainsummit.la/chile2026/ -- these are
    // this stop's own published day themes, not the original bsl2025 hub
    // event's (which agenda.tsx's getTabTheme was previously hardcoded to
    // show for every tour-stop event regardless of which one was open).
    dayThemes: {
      "1": {
        es: "Regulación, Supervisión y Evolución Institucional",
        en: "Regulation, Supervision and Institutional Evolution",
      },
      "2": {
        es: "Tokenización, Stablecoins y Nueva Infraestructura Financiera",
        en: "Tokenization, Stablecoins and New Financial Infrastructure",
      },
      "3": {
        es: "Integración Financiera Global y Sistema Financiero 2030",
        en: "Global Financial Integration and the Financial System of 2030",
      },
    },
    speakers: [
      {
        id: "alberto-naudon",
        name: "Alberto Naudon",
        title: "Vice President",
        company: "Banco Central de Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/alberto-naudon.webp`,
      },
      {
        id: "alvaro-clarke",
        name: "Álvaro Clarke",
        title: "Executive Director of Executive Education",
        company: "Facultad de Economía y Negocios, Universidad de Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/alvaro-clarke.webp`,
      },
      {
        id: "claudia-sotelo",
        name: "Claudia Sotelo",
        title: "Head Financial Innovation Center",
        company: "Comisión para el Mercado Financiero (CMF), Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/claudia-sotelo.webp`,
      },
      {
        id: "francisco-del-olmo",
        name: "Francisco Del Olmo",
        title: "Subdirector responsible for Fintech and Cybersecurity",
        company: "CNMV Spain",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/francisco-del-olmo.webp`,
      },
      {
        id: "renzo-alvarado",
        name: "Renzo Alvarado",
        title: "Principal Supervisor of Market Risk, Liquidity and Investments",
        company: "SBS Peru",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/renzo-alvarado.webp`,
      },
      {
        id: "juan-carlos-reyes",
        name: "Juan Carlos Reyes",
        title: "President",
        company: "Comisión Nacional de Activos Digitales (CNAD), El Salvador",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/juan-carlos-reyes.webp`,
      },
      {
        id: "camila-santana",
        name: "Camila Santana",
        title: "Chief Compliance Officer",
        company: "Banco Revolut",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/camila-santana.webp`,
      },
      {
        id: "daniel-do-nascimento-petiz",
        name: "Daniel do Nascimento Petiz",
        title: "Auditor",
        company: "Banco Central do Brasil (BACEN)",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/daniel-do-nascimento-petiz.webp`,
      },
      {
        id: "ximena-rojas",
        name: "Ximena Rojas",
        title: "VP Legal and Public Affairs",
        company: "Khipu",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/ximena-rojas.webp`,
      },
      {
        id: "jose-manuel-mena",
        name: "José Manuel Mena",
        title: "President",
        company: "Asociación de Bancos e Instituciones Financieras (ABIF)",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/jose-manuel-mena.webp`,
      },
      {
        id: "juan-pablo-cordoba",
        name: "Juan Pablo Córdoba",
        title: "CEO",
        company: "nuam",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/juan-pablo-cordoba.webp`,
      },
      {
        id: "sarina-gowland",
        name: "Sarina Gowland",
        title: "Sales Director",
        company: "Fireblocks",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/sarina-gowland.webp`,
      },
      {
        id: "luisa-cardenas",
        name: "Luisa Cárdenas",
        title: "CEO",
        company: "SURED",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/luisa-cardenas.webp`,
      },
      {
        id: "juan-pablo-rodriguez",
        name: "Juan Pablo Rodríguez",
        title: "Partner",
        company: "RICS Management Colombia and Guatemala",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/juan-pablo-rodriguez.webp`,
      },
      {
        id: "antonio-sundas",
        name: "Antonio Sundas",
        title: "Senior Growth Manager",
        company: "Crypto Finance Group – Deutsche Börse Group",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/antonio-sundas.webp`,
      },
      {
        id: "steffen-harting",
        name: "Steffen Härting",
        title: "Senior Manager",
        company: "Deloitte: Crypto Asset Markets",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/steffen-harting.webp`,
      },
      {
        id: "regina-pedroso",
        name: "Regina Pedroso",
        title: "Executive Director",
        company: "ABToken",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/regina-pedroso.webp`,
      },
      {
        id: "maria-luisa-acuna",
        name: "María Luisa Acuña",
        title: "Cybersecurity Lead Managing Director",
        company: "Accenture Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/maria-luisa-acuna.webp`,
      },
      {
        id: "willian-santos",
        name: "Willian Santos",
        title: "Compliance Manager - Chief Compliance Officer",
        company: "Banco W",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/willian-santos.webp`,
      },
      {
        id: "rafael-teruszkin",
        name: "Rafael Teruszkin",
        title: "Head Latam",
        company: "Bitpanda Technology Solutions",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/rafael-teruszkin.webp`,
      },
      {
        id: "mauricio-jara",
        name: "Mauricio Jara",
        title: "Director",
        company: "Departamento de Administración, FEN-UChile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/mauricio-jara.webp`,
      },
      {
        id: "albi-rodriguez",
        name: "Albi Rodríguez",
        title: "Senior Web3 & DLT Consultant",
        company: "Independent",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/albi-rodriguez.webp`,
      },
      {
        id: "guillermo-acuna",
        name: "Guillermo Acuña",
        title: "Co-founder and CTO",
        company: "Koywe",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/guillermo-acuna.webp`,
      },
      {
        id: "sylvia-sanchez",
        name: "Sylvia Sánchez",
        title: "Project Manager",
        company: "Ava Labs",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/sylvia-sanchez.webp`,
      },
      {
        id: "erick-ortiz",
        name: "Erick Ortiz",
        title: "Blockchain Advisor / Project Manager Digital Payments",
        company: "BBVA Perú",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/erick-ortiz.webp`,
      },
      {
        id: "jose-gabriel-carrasco",
        name: "José Gabriel Carrasco",
        title: "President",
        company: "FinteChile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/jose-gabriel-carrasco.webp`,
      },
      {
        id: "judith-vergara",
        name: "Judith Vergara",
        title: "Director of Executive Education",
        company: "Universidad EAFIT",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/judith-vergara.webp`,
      },
      {
        id: "aldo-fuertes",
        name: "Aldo Fuertes",
        title: "Executive Director",
        company: "Core Capital Group",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/aldo-fuertes.webp`,
      },
      {
        id: "vicente-lazen",
        name: "Vicente Lazen",
        title: "Consultant in capital markets and digital assets",
        company: "Symbioflow.io",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/vicente-lazen.webp`,
      },
      {
        id: "ana-garces",
        name: "Ana Garcés",
        title: "Chief Compliance Officer",
        company: "Banco BHD",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/ana-garces.webp`,
      },
      {
        id: "jaime-bunzli",
        name: "Jaime Bünzli",
        title: "CEO",
        company: "Buda.com",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/jaime-bunzli.webp`,
      },
      {
        id: "guido-messi",
        name: "Guido Messi",
        title: "Head of Corporate Development",
        company: "Ripio",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/guido-messi.webp`,
      },
      {
        id: "daniel-aguilar",
        name: "Daniel Aguilar",
        title: "Co Founder & COO",
        company: "Trokera",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/daniel-aguilar.webp`,
      },
      {
        id: "lissa-parra",
        name: "Lissa Parra",
        title: "Principal Associate",
        company: "Estudio de Abogados Garrigues Colombia",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/lissa-parra.webp`,
      },
      {
        id: "claudio-calderon",
        name: "Claudio Calderón",
        title: "Leader of Strategic Projects",
        company: "Depósito Central de Valores (DCV), Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/claudio-calderon.webp`,
      },
      {
        id: "juan-antonio-figueroa",
        name: "Juan Antonio Figueroa",
        title: "Executive Director",
        company: "ChilePay",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/juan-antonio-figueroa.webp`,
      },
      {
        id: "daniel-hernandez",
        name: "Daniel Hernández",
        title: "Principal Associate",
        company: "Estudio de Abogados Garrigues Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/daniel-hernandez.webp`,
      },
      {
        id: "ignacio-araya",
        name: "Ignacio Araya",
        title: "Commercial Law Professor",
        company: "USACH and Universidad de Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/ignacio-araya.webp`,
      },
      {
        id: "omar-castelblanco",
        name: "Omar Castelblanco",
        title: "Co Founder & CEO",
        company: "Relámpago Payments",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/omar-castelblanco.webp`,
      },
      {
        id: "alexandre-borelli",
        name: "Alexandre Borelli",
        title: "CEO Latin America",
        company: "Alcazar Group",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/alexandre-borelli.webp`,
      },
      {
        id: "nathaly-diniz",
        name: "Nathaly Diniz",
        title: "Chief Revenue Officer",
        company: "Lumx",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/nathaly-diniz.webp`,
      },
      {
        id: "juan-jose-miranda",
        name: "Juan José Miranda",
        title: "Director Innovation Center IC Blockchain/DLT/web3 & QC",
        company: "IBIOL NTT DATA",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/juan-jose-miranda.webp`,
      },
      {
        id: "roberto-darrigrandi",
        name: "Roberto Darrigrandi",
        title: "Partner",
        company: "Altadirección Capital Latam",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/roberto-darrigrandi.webp`,
      },
      {
        id: "stephanie-sanchez",
        name: "Stephanie Sánchez",
        title: "MissCryptoLawyer / Founder & CEO",
        company: "BlockRock",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/stephanie-sanchez.webp`,
      },
      {
        id: "camilo-suarez",
        name: "Camilo Suárez",
        title: "Co Founder & CEO",
        company: "Vurelo",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/camilo-suarez.webp`,
      },
      {
        id: "sebastian-zapata",
        name: "Sebastián Zapata",
        title: "Head of Legal",
        company: "Bitso",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/sebastian-zapata.webp`,
      },
      {
        id: "david-diaz",
        name: "David Díaz",
        title: "Assistant Professor",
        company: "Departamento de Administración, FEN-UChile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/david-diaz.webp`,
      },
      {
        id: "karol-benavides",
        name: "Karol Benavides",
        title: "Regional Head – LATAM Partnerships & Strategy",
        company: "Fiskil",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/karol-benavides.webp`,
      },
      {
        id: "camilo-romero",
        name: "Camilo Romero",
        title: "Consultant in Digital Financial Infrastructure",
        company: "Colombia",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/camilo-romero.webp`,
      },
      {
        id: "bernardo-janot",
        name: "Bernardo Janot",
        title: "LATAM Lead",
        company: "IBM Digital Asset Haven",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/bernardo-janot.webp`,
      },
      {
        id: "jose-manuel-souto",
        name: "José Manuel Souto",
        title: "International Consultant in Compliance and Crypto Assets",
        company: "Grupo Vishab and PRIUS Consulting",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/jose-manuel-souto.webp`,
      },
      {
        id: "fernando-quiros",
        name: "Fernando Quirós",
        title: "Managing Editor",
        company: "Cointelegraph en Español",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/fernando-quiros.webp`,
      },
      {
        id: "leandro-pereira",
        name: "Leandro Pereira",
        title: "VP of LATAM",
        company: "Dfns",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/leandro-pereira.webp`,
      },
      {
        id: "alexis-franco",
        name: "Alexis Franco",
        title: "President",
        company: "Cámara Blockchain Chile",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/alexis-franco.webp`,
      },
      {
        id: "paula-bermudez",
        name: "Paula Bermúdez",
        title: "Lawyer - Founder & CEO",
        company: "Digitalaw (Colombia)",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/paula-bermudez.webp`,
      },
      {
        id: "jorge-corredor",
        name: "Jorge Corredor",
        title: "Assistant Professor and Consultant",
        company: "Universidad Externado Colombia",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/jorge-corredor.webp`,
      },
      {
        id: "gerardo-lagos",
        name: "Gerardo Lagos",
        title: "Co-Founder",
        company: "ObsidiaLab",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/gerardo-lagos.webp`,
      },
      {
        id: "angel-di-matteo",
        name: "Angel Di Matteo",
        title: "Co-Founder and Editor",
        company: "DiarioBitcoin",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/angel-di-matteo.webp`,
      },
      {
        id: "michelle-arguelles",
        name: "Michelle Arguelles",
        title: "CEO",
        company: "M.A Global Accounting",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/michelle-arguelles.webp`,
      },
      {
        id: "rodrigo-sainz",
        name: "Rodrigo Sainz",
        title: "Founder & CEO",
        company: "Blockchain Summit Latam",
        image: `${CHILE2026_SPEAKER_IMAGE_BASE}/rodrigo-sainz.webp`,
      },
      {
        id: "pedro-zegers",
        name: "Pedro Zegers",
        title: "Executive Director",
        company: "ChilePay",
      },
      {
        id: "tomas-dominguez",
        name: "Tomás Domínguez",
        title: "Head of Crypto",
        company: "Koywe",
      },
    ],
    agenda: [
      {
        id: "chile-day1-welcome-cocktail-registration-coffee",
        day: "1",
        time: "08:30-09:30",
        title:
          "Welcome cocktail, registration, coffee & sponsor booths opening",
        type: "registration",
      },
      {
        id: "chile-day1-opening-remarks",
        day: "1",
        time: "09:30-09:40",
        title: "Opening remarks",
        type: "keynote",
        speakers: ["rodrigo-sainz"],
      },
      {
        id: "chile-day1-open-finance-and-regulatory",
        day: "1",
        time: "09:45-10:10",
        title:
          "Open Finance and regulatory transformation of Chilean financial system",
        type: "keynote",
        speakers: ["claudia-sotelo"],
      },
      {
        id: "chile-day1-mica-regulatory-sandboxes-and",
        day: "1",
        time: "10:15-10:40",
        title:
          "MiCA, regulatory sandboxes and evolution of European financial markets",
        type: "keynote",
        speakers: ["francisco-del-olmo"],
      },
      {
        id: "chile-day1-digital-transformation-of-banking",
        day: "1",
        time: "10:45-11:10",
        title:
          "Digital transformation of banking and Latin American financial system evolution",
        type: "keynote",
        speakers: ["jose-manuel-mena"],
      },
      {
        id: "chile-day1-digital-assets-el-salvador",
        day: "1",
        time: "11:15-11:40",
        title: "Digital Assets, El Salvador's experience",
        type: "keynote",
        speakers: ["juan-carlos-reyes"],
      },
      {
        id: "chile-day1-building-new-financial-infrastructure",
        day: "1",
        time: "11:45-12:05",
        title: "Building new financial infrastructure: European perspectives",
        type: "keynote",
        speakers: ["steffen-harting"],
      },
      {
        id: "chile-day1-networking-coffee-lunch-sponsor",
        day: "1",
        time: "12:00-13:00",
        title: "Networking + Coffee lunch + sponsor booths",
        type: "meal",
      },
      {
        id: "chile-day1-virtual-asset-market-regulation",
        day: "1",
        time: "13:00-13:25",
        title:
          "Virtual asset market regulation: comparative perspectives and international evolution",
        type: "keynote",
        speakers: ["daniel-do-nascimento-petiz"],
      },
      {
        id: "chile-day1-panel-financial-infrastructure-and",
        day: "1",
        time: "13:30-14:20",
        title:
          "Panel: Financial infrastructure and banking system transformation",
        type: "panel",
        speakers: [
          "judith-vergara",
          "erick-ortiz",
          "willian-santos",
          "juan-antonio-figueroa",
          "pedro-zegers",
        ],
      },
      {
        id: "chile-day1-compliance-licenses-and-international",
        day: "1",
        time: "14:25-14:50",
        title:
          "Compliance, licenses and international expansion: building global financial institutions",
        type: "keynote",
        speakers: ["camila-santana"],
      },
      {
        id: "chile-day1-panel-new-global-financial",
        day: "1",
        time: "14:55-15:45",
        title:
          "Panel: New global financial architecture: regulation, infrastructure and system transformation",
        type: "panel",
        speakers: [
          "david-diaz",
          "juan-carlos-reyes",
          "daniel-do-nascimento-petiz",
          "francisco-del-olmo",
          "renzo-alvarado",
        ],
      },
      {
        id: "chile-day1-extended-networking-day-1",
        day: "1",
        time: "15:45-16:30",
        title: "Extended networking + Day 1 closing",
        type: "break",
      },
      {
        id: "chile-day2-welcome-coffee-networking-sponsor",
        day: "2",
        time: "08:30-09:30",
        title: "Welcome coffee + networking + sponsor booths opening",
        type: "registration",
      },
      {
        id: "chile-day2-from-traditional-payments-to",
        day: "2",
        time: "09:30-09:55",
        title:
          "From traditional payments to new financial infrastructure: inclusion, interoperability and digital assets",
        type: "keynote",
        speakers: ["luisa-cardenas"],
      },
      {
        id: "chile-day2-panel-capital-markets-in",
        day: "2",
        time: "10:00-10:50",
        title:
          "Panel: Capital markets in transformation: tokenization, new digital assets and institutional adoption",
        type: "panel",
        speakers: [
          "roberto-darrigrandi",
          "alexandre-borelli",
          "rafael-teruszkin",
          "aldo-fuertes",
          "antonio-sundas",
        ],
      },
      {
        id: "chile-day2-from-innovation-to-infrastructure",
        day: "2",
        time: "10:55-11:20",
        title:
          "From innovation to infrastructure: AI, blockchain and financial core modernization",
        type: "keynote",
        speakers: ["juan-jose-miranda"],
      },
      {
        id: "chile-day2-tokenization-evolution-of-the",
        day: "2",
        time: "11:25-11:50",
        title: "Tokenization: Evolution of the financial market",
        type: "keynote",
        speakers: ["rodrigo-sainz"],
      },
      {
        id: "chile-day2-stablecoins-beyond-the-dollar",
        day: "2",
        time: "11:55-12:20",
        title: "Stablecoins, beyond the dollar",
        type: "keynote",
        speakers: ["guillermo-acuna"],
      },
      {
        id: "chile-day2-networking-coffee-lunch-sponsor",
        day: "2",
        time: "12:00-13:00",
        title: "Networking + Coffee lunch + sponsor booths",
        type: "meal",
      },
      {
        id: "chile-day2-workshop-cross-border-payments",
        day: "2",
        time: "11:00-12:00",
        title:
          "Workshop: Your agent operates, you sign: cross-border payments with AI and stablecoins",
        type: "panel",
        speakers: ["tomas-dominguez"],
        location: "Room H202 - Floor 2",
      },
      {
        id: "chile-day2-panel-stablecoins-as-financial",
        day: "2",
        time: "13:00-13:50",
        title:
          "Panel: Stablecoins as financial infrastructure and banking system integration: compliance risks and challenges",
        type: "panel",
        speakers: [
          "juan-pablo-rodriguez",
          "guido-messi",
          "camila-santana",
          "omar-castelblanco",
          "leandro-pereira",
        ],
      },
      {
        id: "chile-day2-cybersecurity-landscape-financial-sector",
        day: "2",
        time: "13:55-14:20",
        title: "Cybersecurity landscape in the financial sector",
        type: "keynote",
        speakers: ["maria-luisa-acuna"],
      },
      {
        id: "chile-day2-panel-new-global-financial",
        day: "2",
        time: "14:25-15:15",
        title:
          "Panel: New global financial architecture: cross-border payments, stablecoins and tokenized financial infrastructure evolution",
        type: "panel",
        speakers: [
          "camilo-romero",
          "luisa-cardenas",
          "sarina-gowland",
          "jaime-bunzli",
          "bernardo-janot",
        ],
      },
      {
        id: "chile-day2-aml-monitoring-and-fraud",
        day: "2",
        time: "15:20-15:45",
        title:
          "AML monitoring and fraud prevention synergies in the compliance world",
        type: "keynote",
        speakers: ["willian-santos"],
      },
      {
        id: "chile-day2-extended-networking-day-2",
        day: "2",
        time: "15:45-16:30",
        title: "Extended networking + Day 2 closing",
        type: "break",
      },
      {
        id: "chile-day3-welcome-coffee-networking-sponsor",
        day: "3",
        time: "08:30-09:30",
        title: "Welcome coffee + networking + sponsor booths opening",
        type: "registration",
      },
      {
        id: "chile-day3-chile-facing-the-new",
        day: "3",
        time: "09:30-09:55",
        title: "Global stablecoins, stability and innovation",
        type: "keynote",
        speakers: ["alberto-naudon"],
      },
      {
        id: "chile-day3-panel-digital-assets-architecture",
        day: "3",
        time: "10:00-10:50",
        title:
          "Panel: Digital assets architecture: regulation, market and institutional adoption",
        type: "panel",
        speakers: [
          "paula-bermudez",
          "daniel-hernandez",
          "sylvia-sanchez",
          "ximena-rojas",
          "ignacio-araya",
        ],
      },
      {
        id: "chile-day3-fireside-chat-from-innovation",
        day: "3",
        time: "10:55-11:20",
        title:
          "Fireside chat: From innovation to infrastructure: building programmable financial systems",
        type: "panel",
        speakers: ["albi-rodriguez", "francisco-del-olmo"],
      },
      {
        id: "chile-day3-panel-convergence-between-banking",
        day: "3",
        time: "11:25-12:15",
        title:
          "Panel: Convergence between banking, capital markets and digital assets: emerging models and opportunities for the financial system",
        type: "panel",
        speakers: [
          "mauricio-jara",
          "juan-pablo-cordoba",
          "jose-manuel-souto",
          "regina-pedroso",
          "vicente-lazen",
        ],
      },
      {
        id: "chile-day3-panel-financial-system-2030",
        day: "3",
        time: "12:20-13:10",
        title:
          "Panel: Financial System 2030: how will money, capital and financial infrastructure be redefined?",
        type: "panel",
        speakers: [
          "alvaro-clarke",
          "jose-gabriel-carrasco",
          "alexis-franco",
          "guillermo-acuna",
          "claudio-calderon",
        ],
      },
      {
        id: "chile-day3-conclusions-and-closing",
        day: "3",
        time: "13:15-13:30",
        title: "Conclusions and closing",
        type: "keynote",
        speakers: ["mauricio-jara", "rodrigo-sainz"],
      },
    ],
  }),
  colombia2026: makeTourStopConfig("colombia2026", {
    name: "BSL Colombia 2026",
    title: "Blockchain Summit Latam Colombia 2026",
    subtitle: "Bogotá, Colombia",
    // Shared regional call for speakers (Colombia Blockchain Week's own form,
    // not a BSL-run CFP) -- surfaced here per explicit request to cross-promote
    // it on this event's page too, alongside its organizer's own cbweek2026 page.
    speakerApplicationUrl: "https://colombiablockchainweek.com/ser-speaker#postulacion",
    aliases: [
      "BSL Colombia",
      "BSL Colombia 2026",
      "BSL Bogotá",
      "BSL Bogota",
      "Blockchain Summit Colombia",
      "Blockchain Summit Bogotá",
      "Blockchain Summit Bogota",
      "Blockchain Summit Latam Colombia",
      "Blockchain Summit Latam Colombia 2026",
      "#bsl2026",
      "#bslcolombia2026",
    ],
    color: "#F5C542",
    eventStartDate: "2026-11-04T08:00:00-05:00",
    eventEndDate: "2026-11-06T23:59:59-05:00",
    eventDateString: "November 4-6, 2026 • Bogotá, Colombia",
    city: "Bogotá",
    country: "Colombia",
    continent: "South America",
    venue:
      "Edificios H e I · Universidad Externado de Colombia, La Candelaria, Bogotá",
    summary:
      "Institutional and regulatory summit for the Andean region with Banco de la República.",
    stopOrder: 3,
    image: "/assets/logos/bsl/bsl-colombia-pro.svg",
    brandingLogo: "/assets/logos/bsl/bsl-colombia-pro.svg",
    speakers: [
      {
        id: "ana-maria-prieto",
        name: "Ana María Prieto",
        title: "Directora de Sistemas de Pago",
        company: "Banco de la República de Colombia",
        bio: "Directora de Sistemas de Pago · Banco de la República de Colombia",
      },
      {
        id: "juan-pablo-cordoba",
        name: "Juan Pablo Córdoba",
        title: "CEO",
        company: "nuam",
        bio: "CEO · nuam",
      },
      {
        id: "juan-carlos-reyes",
        name: "Juan Carlos Reyes",
        title: "Presidente",
        company: "Comisión Nacional de Activos Digitales (CNAD), El Salvador",
        bio: "Presidente · Comisión Nacional de Activos Digitales (CNAD), El Salvador",
      },
      {
        id: "shenny-gonzalez",
        name: "Shenny González",
        title: "Presidenta",
        company: "Asobolsa",
        bio: "Presidenta · Asobolsa",
      },
      {
        id: "nagel-paulino",
        name: "Nagel Paulino",
        title: "Jefe de División",
        company: "Departamento de Regulación, Banco Central de Brasil",
        bio: "Jefe de División · Departamento de Regulación, Banco Central de Brasil",
      },
      {
        id: "carol-baez",
        name: "Carol Báez",
        title: "Vicepresidente Jurídica y Secretaria General",
        company: "Bolsa Mercantil de Colombia",
        bio: "Vicepresidente Jurídica y Secretaria General · Bolsa Mercantil de Colombia",
      },
      {
        id: "nicolas-molina",
        name: "Nicolás Molina",
        title: "Gerente de Ingeniería de Productos Digitales",
        company: "Banco Popular",
        bio: "Gerente de Ingeniería de Productos Digitales · Banco Popular",
      },
      {
        id: "juan-sebastian-peredo",
        name: "Juan Sebastián Peredo",
        title: "Vicepresidente Jurídico",
        company: "Lulo Bank",
        bio: "Vicepresidente Jurídico · Lulo Bank",
      },
      {
        id: "willian-santos",
        name: "Willian Santos",
        title: "Gerente de Compliance",
        company: "Oficial de Cumplimiento, Banco W",
        bio: "Gerente de Compliance · Oficial de Cumplimiento, Banco W",
      },
      {
        id: "regina-pedroso",
        name: "Regina Pedroso",
        title: "Directora Ejecutiva",
        company: "ABToken, Brasil",
        bio: "Directora Ejecutiva · ABToken, Brasil",
      },
      {
        id: "jorge-corredor",
        name: "Jorge Corredor",
        title: "Docente Universidad Externado",
        company: "Derecho bancario, mercado de valores, Web3 y tokenización",
        bio: "Docente Universidad Externado · Derecho bancario, mercado de valores, Web3 y tokenización",
      },
      {
        id: "nubia-liliana-abril-rios",
        name: "Nubia Liliana Abril Ríos",
        title: "Clúster de Servicios Financieros",
        company: "Cámara de Comercio de Bogotá",
        bio: "Clúster de Servicios Financieros · Cámara de Comercio de Bogotá",
      },
      {
        id: "judith-vergara",
        name: "Judith Vergara",
        title: "Director of Executive Education",
        company: "School of Finance, Economics and Government, Universidad EAFIT",
        bio: "Director of Executive Education · School of Finance, Economics and Government, Universidad EAFIT",
      },
      {
        id: "rafael-teruszkin",
        name: "Rafael Teruszkin",
        title: "Head Latam",
        company: "Bitpanda Enterprise",
        bio: "Head Latam · Bitpanda Enterprise",
      },
      {
        id: "lissa-parra",
        name: "Lissa Parra",
        title: "Asociada Principal",
        company: "Garrigues Colombia",
        bio: "Asociada Principal · Garrigues Colombia",
      },
      {
        id: "aldo-fuertes",
        name: "Aldo Fuertes",
        title: "Presidente del Consejo Consultivo de Mercados Capitales del Perú",
        company: "",
        bio: "Presidente del Consejo Consultivo de Mercados Capitales del Perú",
      },
      {
        id: "luisa-cardenas",
        name: "Luisa Cárdenas",
        title: "CEO",
        company: "SURED",
        bio: "CEO · SURED",
      },
      {
        id: "omar-castelblanco",
        name: "Omar Castelblanco",
        title: "Co-Founder & CEO",
        company: "Relámpago Payments",
        bio: "Co-Founder & CEO · Relámpago Payments",
      },
      {
        id: "juan-pablo-rodriguez",
        name: "Juan Pablo Rodríguez",
        title: "Socio",
        company: "RICS Management Colombia y Guatemala",
        bio: "Socio · RICS Management Colombia y Guatemala",
      },
      {
        id: "miguel-calero",
        name: "Miguel Calero",
        title: "Executive Director",
        company: "ISBE / Alastria",
        bio: "Executive Director · ISBE / Alastria",
      },
      {
        id: "luis-miguel-arroyave",
        name: "Luis Miguel Arroyave",
        title: "Sales Director",
        company: "Fireblocks",
        bio: "Sales Director · Fireblocks",
      },
      {
        id: "sebastian-zapata",
        name: "Sebastián Zapata",
        title: "Universidad Externado",
        company: "Head of Legal, Bitso",
        bio: "Universidad Externado · Head of Legal, Bitso",
      },
      {
        id: "sergio-covaleda",
        name: "Sergio Covaleda",
        title: "Chief Legal Officer (CLO)",
        company: "Wenia",
        bio: "Chief Legal Officer (CLO) · Wenia",
      },
      {
        id: "eduardo-sanmiguel-gomez",
        name: "Eduardo Sanmiguel Gómez",
        title: "Head of Legal",
        company: "Revolut Colombia",
        bio: "Head of Legal · Revolut Colombia",
      },
      {
        id: "camilo-gantiva-hidalgo",
        name: "Camilo Gantiva Hidalgo",
        title: "Socio",
        company: "Holland & Knight",
        bio: "Socio · Holland & Knight",
      },
      {
        id: "rodrigo-sainz",
        name: "Rodrigo Sainz",
        title: "Founder & CEO",
        company: "Blockchain Summit Latam",
        bio: "Founder & CEO · Blockchain Summit Latam",
      },
    ],
    agenda: ([
      {
        id: "colombia2026-day1-01-welcome-coffee-acreditacion-networking-y-apertura-de-stands",
        day: "1",
        time: "08:00 - 09:00",
        title: "Welcome Coffee, acreditación, networking y apertura de stands",
        type: "networking",
      },
      {
        id: "colombia2026-day1-02-palabras-de-apertura",
        day: "1",
        time: "09:00 - 09:15",
        title: "Palabras de Apertura",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-03-interoperabilidad-pagos-de-alto-valor-y-dinero-digital-el-nuevo-mapa-de-infraestructura",
        day: "1",
        time: "09:15 - 09:40",
        title: "Interoperabilidad, pagos de alto valor y dinero digital: el nuevo mapa de infraestructura",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-04-de-la-supervision-tradicional-a-los-activos-digitales-prioridades-regulatorias-para-colombia",
        day: "1",
        time: "09:45 - 10:10",
        title: "De la supervisión tradicional a los activos digitales: prioridades regulatorias para Colombia",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-05-un-mercado-tres-economias-como-nuam-esta-construyendo-la-nueva-infraestructura-regional-de-capitales",
        day: "1",
        time: "10:15 - 10:40",
        title: "Un mercado, tres economías: cómo nuam está construyendo la nueva infraestructura regional de capitales",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-06-el-salvador-despues-de-la-ley-de-activos-digitales-lecciones-desde-la-regulacion-y-el-mercado",
        day: "1",
        time: "10:45 - 11:10",
        title: "El Salvador después de la Ley de Activos Digitales: lecciones desde la regulación y el mercado",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-07-coffee-brunch-networking-stands",
        day: "1",
        time: "11:10 - 11:50",
        title: "Coffee Brunch + networking + stands",
        type: "meal",
      },
      {
        id: "colombia2026-day1-08-finanzas-abiertas-y-tokenizacion-la-proxima-agenda-regulatoria-de-colombia",
        day: "1",
        time: "11:50 - 12:45",
        title: "Finanzas abiertas y tokenización: la próxima agenda regulatoria de Colombia",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-09-brasil-frente-a-los-activos-virtuales-marco-regulatorio-supervision-y-evolucion-del-mercado",
        day: "1",
        time: "12:20 - 12:45",
        title: "Brasil frente a los activos virtuales: marco regulatorio, supervisión y evolución del mercado",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-10-el-sistema-financiero-en-transformacion-infraestructura-innovacion-y-nuevos-modelos-institucionales",
        day: "1",
        time: "12:50 - 13:40",
        title: "El sistema financiero en transformación: infraestructura, innovación y nuevos modelos institucionales",
        type: "panel",
      },
      {
        id: "colombia2026-day1-11-como-integrar-stablecoins-en-banca-controles-gobernanza-y-operacion",
        day: "1",
        time: "13:45 - 14:10",
        title: "Cómo integrar stablecoins en banca: controles, gobernanza y operación",
        type: "keynote",
      },
      {
        id: "colombia2026-day1-12-de-la-regulacion-al-mercado-que-falta-para-escalar-los-activos-digitales-en-america-latina",
        day: "1",
        time: "14:15 - 15:05",
        title: "De la regulación al mercado: qué falta para escalar los activos digitales en América Latina",
        type: "panel",
      },
      {
        id: "colombia2026-day1-13-coffee-de-cierre-networking-stands",
        day: "1",
        time: "15:05 - 16:00",
        title: "Coffee de cierre + networking + stands",
        type: "networking",
      },
      {
        id: "colombia2026-day2-01-welcome-coffee-networking-apertura-de-stands",
        day: "2",
        time: "08:00 - 09:00",
        title: "Welcome Coffee + networking + apertura de stands",
        type: "networking",
      },
      {
        id: "colombia2026-day2-02-bre-b-y-el-salto-a-los-pagos-inmediatos-que-cambia-para-colombia",
        day: "2",
        time: "09:00 - 09:25",
        title: "Bre-B y el salto a los pagos inmediatos: qué cambia para Colombia",
        type: "keynote",
      },
      {
        id: "colombia2026-day2-03-mercados-de-capitales-tokenizados-nuevos-activos-y-adopcion-institucional",
        day: "2",
        time: "09:30 - 10:20",
        title: "Mercados de capitales tokenizados: nuevos activos y adopción institucional",
        type: "panel",
      },
      {
        id: "colombia2026-day2-04-activos-digitales-como-motor-de-inclusion-financiera-el-caso-colombiano",
        day: "2",
        time: "10:25 - 10:50",
        title: "Activos digitales como motor de inclusión financiera: el caso colombiano",
        type: "keynote",
      },
      {
        id: "colombia2026-day2-05-stablecoins-como-rail-financiero-pagos-liquidez-y-nueva-infraestructura-monetaria",
        day: "2",
        time: "10:55 - 11:20",
        title: "Stablecoins como rail financiero: pagos, liquidez y nueva infraestructura monetaria",
        type: "keynote",
      },
      {
        id: "colombia2026-day2-06-coffee-brunch-networking-stands",
        day: "2",
        time: "11:20 - 12:00",
        title: "Coffee Brunch + networking + stands",
        type: "meal",
      },
      {
        id: "colombia2026-day2-07-stablecoins-mas-alla-del-dolar-nuevos-usos-monedas-y-mercados",
        day: "2",
        time: "12:00 - 12:25",
        title: "Stablecoins más allá del dólar: nuevos usos, monedas y mercados",
        type: "keynote",
      },
      {
        id: "colombia2026-day2-08-stablecoins-a-escala-institucional-integracion-compliance-y-gestion-de-riesgos",
        day: "2",
        time: "12:30 - 13:20",
        title: "Stablecoins a escala institucional: integración, compliance y gestión de riesgos",
        type: "panel",
      },
      {
        id: "colombia2026-day2-09-autocustodia-para-mercados-emergentes-inclusion-financiera-desde-fedi",
        day: "2",
        time: "13:25 - 13:50",
        title: "Autocustodia para mercados emergentes: inclusión financiera desde Fedi",
        type: "keynote",
      },
      {
        id: "colombia2026-day2-10-pagos-transfronterizos-y-finanzas-tokenizadas-stablecoins-y-nueva-infraestructura-global",
        day: "2",
        time: "13:55 - 14:45",
        title: "Pagos transfronterizos y finanzas tokenizadas: stablecoins y nueva infraestructura global",
        type: "panel",
      },
      {
        id: "colombia2026-day2-11-escalar-una-fintech-global-licencias-compliance-y-expansion-internacional",
        day: "2",
        time: "14:50 - 15:15",
        title: "Escalar una fintech global: licencias, compliance y expansión internacional",
        type: "keynote",
      },
      {
        id: "colombia2026-day2-12-coffee-de-cierre-networking-stands",
        day: "2",
        time: "15:15 - 16:10",
        title: "Coffee de cierre + networking + stands",
        type: "networking",
      },
      {
        id: "colombia2026-day3-01-welcome-coffee-networking-apertura-de-stands",
        day: "3",
        time: "08:00 - 09:00",
        title: "Welcome Coffee + networking + apertura de stands",
        type: "networking",
      },
      {
        id: "colombia2026-day3-02-cuando-el-avance-en-infraestructura-financiera-modifica-el-mercado-de-capitales",
        day: "3",
        time: "09:00 - 09:25",
        title: "Cuando el avance en infraestructura financiera modifica el mercado de capitales *",
        type: "keynote",
      },
      {
        id: "colombia2026-day3-03-confianza-en-los-activos-digitales-regulacion-ciberseguridad-y-gobernanza-institucional",
        day: "3",
        time: "09:30 - 10:20",
        title: "Confianza en los activos digitales: regulación, ciberseguridad y gobernanza institucional",
        type: "panel",
      },
      {
        id: "colombia2026-day3-04-activos-digitales-a-escala-institucional-custodia-seguridad-y-confianza-para-el-sistema-financiero",
        day: "3",
        time: "10:25 - 10:50",
        title: "Activos digitales a escala institucional: custodia, seguridad y confianza para el sistema financiero",
        type: "keynote",
      },
      {
        id: "colombia2026-day3-05-banca-mercados-de-capitales-y-activos-digitales-convergencia-y-nuevas-oportunidades",
        day: "3",
        time: "10:55 - 11:45",
        title: "Banca, mercados de capitales y activos digitales: convergencia y nuevas oportunidades",
        type: "panel",
      },
      {
        id: "colombia2026-day3-06-coffee-brunch-networking-stands",
        day: "3",
        time: "11:45 - 12:25",
        title: "Coffee Brunch + networking + stands",
        type: "meal",
      },
      {
        id: "colombia2026-day3-07-sistema-financiero-2030-el-futuro-del-dinero-el-capital-y-la-infraestructura",
        day: "3",
        time: "12:25 - 13:15",
        title: "Sistema Financiero 2030: el futuro del dinero, el capital y la infraestructura",
        type: "panel",
      },
      {
        id: "colombia2026-day3-08-de-la-innovacion-a-escala-nuevos-modelos-financieros-en-colombia",
        day: "3",
        time: "13:20 - 14:10",
        title: "De la innovación a escala: nuevos modelos financieros en Colombia",
        type: "panel",
      },
      {
        id: "colombia2026-day3-09-de-la-infraestructura-financiera-a-las-finanzas-programables-la-proxima-decada-del-dinero-y-los-mercados",
        day: "3",
        time: "14:15 - 14:40",
        title: "De la infraestructura financiera a las finanzas programables: la próxima década del dinero y los mercados *",
        type: "keynote",
      },
      {
        id: "colombia2026-day3-10-conclusiones-y-clausura",
        day: "3",
        time: "14:40 - 15:00",
        title: "Conclusiones y Clausura",
        type: "keynote",
      },
      {
        id: "colombia2026-day3-11-coffee-final-networking-stands",
        day: "3",
        time: "15:00 - 15:30",
        title: "Coffee final + networking + stands",
        type: "networking",
      },
    ] satisfies AgendaItem[]).map((item): AgendaItem => ({
      ...item,
      // These are the room labels published on the official Colombia 2026
      // programme. Keeping them on every fallback row also selects the
      // matching bundled Externado image in the agenda card.
      location: item.type === "panel"
        ? "Panel central"
        : item.type === "networking" || item.type === "meal"
          ? "Hall principal"
          : "Auditorio",
    })),
  }),
  bsl2025: {
    id: "bsl2025",
    name: "BSL 2025",
    domain: "bsl2025.hashpass.tech",
    website: "https://blockchainsummit.la/",
    title: "Blockchain Summit Latam 2025",
    subtitle: "Universidad EAFIT, Medellín",
    image: "/assets/images/bsl2025-hero.svg",
    heroVideo: eventHeroVideo("bsl2025"),
    heroPoster: eventHeroPoster("bsl2025"),
    color: "#2196F3",
    eventStartDate: "2025-11-12T09:00:00-05:00",
    eventEndDate: "2025-11-14T23:59:59-05:00",
    eventDateString: "November 12-14, 2025 • Medellín, Colombia",
    series: "Summit",
    geo: {
      country: "Colombia",
      continent: "South America",
    },
    features: ["matchmaking", "speakers", "bookings", "admin"],
    eventType: "whitelabel",
    branding: {
      primaryColor: "#2196F3",
      secondaryColor: "#34A853",
      logo: "/assets/logos/bsl/BSL-Logo-fondo-oscuro-2024.svg",
      favicon: "/favicon.ico",
    },
    api: {
      basePath: "/api/bsl",
      endpoints: {
        speakers: "speakers",
        bookings: "bookings",
        "verify-ticket": "verify-ticket",
        "auto-match": "auto-match",
        agenda: "agenda",
        status: "status",
      },
    },
    routes: {
      home: "/events/bsl2025/home",
      speakers: "/events/bsl2025/speakers",
      bookings: "/events/bsl2025/my-bookings",
      admin: "/events/bsl2025/admin",
    },
    database: {
      schema: "bsl",
      tables: {
        speakers: "bsl_speakers",
        bookings: "bsl_bookings",
        attendees: "bsl_attendees",
      },
    },
    tour: {
      hubEventId: "bsl",
      role: "archive",
      stopOrder: 99,
      city: "Medellín",
      country: "Colombia",
      venue: "Universidad EAFIT",
      summary: "Archived 2025 edition of Blockchain Summit Latam.",
    },
    speakers: [
      {
        id: "550e8400-e29b-41d4-a716-446655440001",
        name: "Claudia Restrepo",
        title: "Rectora",
        company: "EAFIT",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440002",
        name: "Leonardo Villar",
        title: "Gerente General",
        company: "Banco de la República",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440003",
        name: "César Ferrari",
        title: "Superintendente Financiero de Colombia",
        company: "Superintendencia Financiera",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440004",
        name: "Alberto Naudon",
        title: "Consejero",
        company: "Banco Central de Chile",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440005",
        name: "José Outumuro",
        title: "Director Institutional sales EMEA",
        company: "Crypto.com",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440006",
        name: "Efraín Barraza",
        title: "Regional Expansion Manager - Latam",
        company: "Tether",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440007",
        name: "Sandra Meza",
        title: "Vicepresidente Control Interno y Cumplimiento",
        company: "BBVA",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440008",
        name: "Sebastián Durán",
        title: "Subdirector de Regulación",
        company: "Superintendencia Financiera de Colombia",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440009",
        name: "Rocelo Lopes",
        title: "CEO",
        company: "SmartPay",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440010",
        name: "Ana Garcés",
        title: "Chief Compliance Officer",
        company: "Banco BHD",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440011",
        name: "Juan Carlos Reyes",
        title: "Presidente",
        company: "Comisión Nacional de Activos Digitales (CNAD) El Salvador",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440012",
        name: "Gabriel Santos",
        title: "Presidente Ejecutivo",
        company: "Colombia FinTech",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440013",
        name: "César Tamayo",
        title: "Dean, School of Finance, Economics & Government",
        company: "Universidad EAFIT",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440014",
        name: "Daniel Mangabeira",
        title: "Vice President Strategy & Policy, Brazil & Latin America",
        company: "Circle",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440015",
        name: "Juan Pablo Rodríguez",
        title: "Socio de rics management",
        company: "Colombia y Guatemala",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440016",
        name: "Willian Santos",
        title: "Gerente de Compliance - Oficial de Cumplimiento",
        company: "Banco W",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440017",
        name: "Rocío Alvarez-Ossorio",
        title: "Founder & CEO",
        company: "Hator",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440018",
        name: "Steffen Härting",
        title: "Senior Manager",
        company: "Deloitte: Crypto Asset Markets",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440019",
        name: "Diego Fernández",
        title: "Gerente Corporativo de Innovación",
        company: "nuam",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440020",
        name: "Andres Florido",
        title: "Senior Manager - Blockchain & AI Assurance",
        company: "Deloitte",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440021",
        name: "Liz Bejarano",
        title: "Directora Financiera y de Riesgo",
        company: "Asobancaria",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440022",
        name: "Andrés Meneses",
        title: "Founder",
        company: "Orbyt X",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440023",
        name: "Luther Maday",
        title: "Head of Payments",
        company: "Algorand Foundation",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440024",
        name: "Rafael Teruszkin",
        title: "Head Latam",
        company: "Bitpanda Technology Solutions",
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440025",
        name: "Albi Rodríguez",
        title: "Senior Web3 & DLT Consultant",
        company: "Independent",
      },
      {
        id: "26",
        name: "Judith Vergara",
        title: "Director of Executive Education",
        company: "Universidad EAFIT",
      },
      {
        id: "27",
        name: "William Durán",
        title: "CO-CEO & Founder",
        company: "Minteo",
      },
      {
        id: "28",
        name: "Daniel Aguilar",
        title: "Co Founder & COO",
        company: "Trokera",
      },
      {
        id: "29",
        name: "Rafael Gago",
        title: "Director Comercial, Gerencia de Ideación e Incubación",
        company: "nuam exchange",
      },
      {
        id: "30",
        name: "Pablo Santos",
        title: "Founder & CEO",
        company: "Finaktiva",
      },
      {
        id: "31",
        name: "Ana María Zuluaga",
        title: "Head of Open Finance Office",
        company: "Grupo Aval",
      },
      {
        id: "32",
        name: "Alireza Siadat",
        title: "Head of Strategy and Policy",
        company: "1inch",
      },
      {
        id: "33",
        name: "Omar Castelblanco",
        title: "Co Founder & CEO",
        company: "Relámpago Payments",
      },
      {
        id: "34",
        name: "Juan Pablo Salazar",
        title: "Head of Legal, Regulatory Affairs y Compliance",
        company: "Ripio USA y Colombia",
      },
      {
        id: "35",
        name: "Pedro Gutiérrez",
        title: "Head of Partnerships",
        company: "LNET",
      },
      {
        id: "36",
        name: "Marcos Carpio",
        title: "Co-Founder & CFO",
        company: "Tokelab",
      },
      {
        id: "37",
        name: "Nathaly Diniz",
        title: "Chief Revenue Officer",
        company: "Lumx",
      },
      {
        id: "38",
        name: "Santiago Mejía",
        title: "Chief Sales Officer",
        company: "Lulo bank",
      },
      {
        id: "39",
        name: "Andrés González",
        title: "Co Founder & CEO",
        company: "indahouse",
      },
      {
        id: "40",
        name: "Stephanie Sánchez",
        title: "Asociada",
        company: "Fayca",
      },
      {
        id: "41",
        name: "Albert Prat",
        title: "Fundador",
        company: "Beself Brands",
      },
      {
        id: "42",
        name: "Mónica Arellano",
        title: "Managing Director - Stablecoins",
        company: "Anchorage",
      },
      {
        id: "43",
        name: "Camilo Suárez",
        title: "Co Founder & CEO",
        company: "Vurelo",
      },
      {
        id: "44",
        name: "Daniel Marulanda",
        title: "Co Founder & CEO",
        company: "Trokera",
      },
      {
        id: "45",
        name: "Carlos Salinas",
        title: "Head of Digital Assets",
        company: "Mora Banc",
      },
      {
        id: "46",
        name: "David Yao",
        title: "Principal",
        company: "LBanks Labs",
      },
      {
        id: "47",
        name: "María Fernanda Marín",
        title: "Compliance Officer",
        company: "DJIRO",
      },
      {
        id: "48",
        name: "Kieve Huffman",
        title: "Founder and Chief Revenue Officer",
        company: "Engager",
      },
      {
        id: "49",
        name: "Matias Marmisolle",
        title: "Co Founder & CEO",
        company: "Anzi Finance",
      },
      {
        id: "50",
        name: "Karol Benavides",
        title: "Regional Head – LATAM Partnerships & Strategy",
        company: "Fiskil",
      },
      {
        id: "51",
        name: "Camilo Romero",
        title: "Co Fundador y CEO",
        company: "Spyral Labs",
      },
      {
        id: "52",
        name: "José Manuel Souto",
        title: "Consultor Internacional en Compliance y Criptoactivos",
        company: "Grupo Vishab y PRIUS Consulting",
      },
      {
        id: "53",
        name: "Edison Montoya",
        title: "Director",
        company: "Finhub EAFIT",
      },
      {
        id: "54",
        name: "Fernando Quirós",
        title: "Managing Editor",
        company: "Cointelegraph en Español",
      },
      {
        id: "55",
        name: "Mariangel García",
        title: "Co-Founder",
        company: "Women In Investment Network",
      },
      { id: "56", name: "Edward Calderón", title: "CEO", company: "HASHPASS" },
      {
        id: "57",
        name: "Roberto Darrigrandi",
        title: "Socio",
        company: "Altadirección Capital Latam",
      },
      {
        id: "58",
        name: "Ed Marquez",
        title: "Head of Developer Relations",
        company: "Hashgraph",
      },
      {
        id: "59",
        name: "Diego Osuna",
        title: "CEO y Co Founder",
        company: "MonaBit",
      },
      {
        id: "60",
        name: "Paula Bermúdez",
        title: "Abogada - Founder & CEO",
        company: "Digitalaw",
      },
      {
        id: "61",
        name: "Gerardo Lagos",
        title: "Co-Founder",
        company: "ObsidiaLab",
      },
      {
        id: "62",
        name: "Mireya Acosta",
        title: "Co founder",
        company: "ColocaPayments",
      },
      { id: "63", name: "0xj4an", title: "Advisor", company: "Celo Colombia" },
      {
        id: "64",
        name: "Camilo Serna",
        title: "Head of Product",
        company: "Kravata",
      },
      {
        id: "65",
        name: "Michelle Arguelles",
        title: "CEO",
        company: "M.A Global Accounting",
      },
      {
        id: "66",
        name: "Sebastián Ramírez",
        title: "Developer",
        company: "TuCOP",
      },
      {
        id: "67",
        name: "Ximena Monclou",
        title: "Abogada y Contadora",
        company: "Celo Colombia",
      },
      {
        id: "68",
        name: "Oscar Moratto",
        title: "Director General",
        company: "Beyond Risk SAS",
      },
      {
        id: "69",
        name: "Rodrigo Sainz",
        title: "Founder & CEO",
        company: "Blockchain Summit Latam",
      },
    ],
    agenda: [
      {
        id: "1",
        time: "08:00 - 09:00",
        title: "Registro y café de bienvenida",
        type: "registration",
      },
      {
        id: "2",
        time: "09:00 - 09:15",
        title: "Palabras de apertura – Rectora de la Universidad EAFIT",
        type: "keynote",
        speakers: ["Claudia Restrepo"],
      },
      {
        id: "3",
        time: "09:20 – 09:45",
        title: 'Keynote – "Red regional de pruebas para dinero tokenizado"',
        type: "keynote",
      },
      {
        id: "4",
        time: "09:50 – 10:25",
        title: 'Keynote – "Infraestructura Financiera Global del Futuro"',
        type: "keynote",
      },
      {
        id: "5",
        time: "10:35 – 11:05",
        title:
          'Keynote – Colombia Fintech – "El Rol de las Fintech en la Adopción del Dinero Digital en América Latina"',
        type: "keynote",
        speakers: ["Gabriel Santos"],
      },
      {
        id: "6",
        time: "11:10 – 11:45",
        title:
          'Keynote – Superintendencia Financiera de Colombia – "El futuro de la supervisión y regulación financiera en la era digital"',
        type: "keynote",
        speakers: ["César Ferrari"],
      },
      {
        id: "7",
        time: "11:50 – 13:00",
        title: 'Panel – "CBDCs y el Futuro del Dinero en LatAm"',
        type: "panel",
      },
      { id: "8", time: "13:00 – 14:30", title: "Almuerzo Libre", type: "meal" },
      {
        id: "9",
        time: "14:35 – 15:05",
        title:
          'Keynote – "Activos Digitales, Blockchain y Tokenización de Activos"',
        type: "keynote",
      },
      {
        id: "10",
        time: "15:10 – 16:20",
        title:
          'Panel (Bancos Comerciales) – "Transformación Digital de la Banca Tradicional"',
        type: "panel",
      },
      {
        id: "11",
        time: "16:25 – 17:35",
        title:
          'Panel (Reguladores) – "Marco regulatorio para la innovación financiera en LatAm"',
        type: "panel",
      },
      {
        id: "12",
        time: "17:40 – 18:30",
        title:
          'Panel – "El Futuro del Dinero Digital: Innovación, Confianza y Colaboración en LATAM"',
        type: "panel",
      },
    ],
    quickAccessItems: [
      {
        id: "agenda",
        title: "Event Agenda",
        subtitle: "3 Days Schedule",
        icon: "event",
        color: "#34A853",
        route: "/events/bsl2025/agenda",
      },
      {
        id: "networking",
        title: "Networking Center",
        subtitle: "Connect & meet",
        icon: "people-alt",
        color: "#4CAF50",
        route: "/events/bsl2025/networking",
      },
      {
        id: "speakers",
        title: "Featured Speakers",
        subtitle: "Meet the experts",
        icon: "people",
        color: "#007AFF",
        route: "/events/bsl2025/speakers/calendar",
      },
      {
        id: "event-info",
        title: "Event Information",
        subtitle: "Details & Logistics",
        icon: "info",
        color: "#FF9500",
        route: "/events/bsl2025/event-info",
      },
    ],
  },
  ...(HASH_POKER_EVENT ? { "hash-poker": HASH_POKER_EVENT } : {}),
  cbweek2026: {
    id: "cbweek2026",
    name: "Colombia Blockchain Week 2026",
    shortName: "CBW",
    aliases: [
      "cbw",
      "cbweek",
      "cbw2026",
      "cbweek2026",
      "CB Week",
      "CB Week 2026",
      "Colombia Blockchain Week",
      "Colombia Blockchain Week 2026",
      "Medellin CBWeek",
      "Medellín CBWeek",
      "Medellin Blockchain Week",
      "Medellín Blockchain Week",
      "Blockchain Week Medellin",
      "Blockchain Week Medellín",
      "#cbw2026",
      "#cbweek2026",
    ],
    domain: "cbweek2026.hashpass.tech",
    website: "https://colombiablockchainweek.com/",
    speakerApplicationUrl: "https://colombiablockchainweek.com/ser-speaker#postulacion",
    title: "Colombia Blockchain Week 2026",
    subtitle: "Hotel InterContinental Medellín • 1ª Edición",
    // Official Colombia Blockchain Week assets, downloaded from the event's
    // own published media library and re-hosted on HashPass event media.
    image: "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/cbweek2026/branding/cbweek2026-hero.jpg",
    // A clean city film is safe under live event copy; the official flyer is
    // retained above as a standalone image asset, never a banner background.
    heroVideo: eventHeroVideo("cbweek2026"),
    heroPoster: eventHeroPoster("cbweek2026"),
    bannerSlides: [
      {
        id: "cbweek-2026",
        media: {
          // Reviewed HASHPASS-branded motion loop. The official flyer remains
          // the loading/failure image rather than being used behind live copy.
          type: "video",
          url: eventHeroVideo("cbweek2026"),
        },
        eyebrow: "CBW 2026 · 1ª Edición",
        title: "Colombia Blockchain Week 2026",
        subtitle: "Hotel InterContinental Medellín · El Poblado",
        date: "December 11-12, 2026 · Medellín, Colombia",
        cta: {
          label: "Explore Colombia Blockchain Week",
          url: "/events/cbweek2026/home",
        },
      },
    ],
    color: "#FCD116",
    eventStartDate: "2026-12-12T08:30:00-05:00",
    eventEndDate: "2026-12-12T18:00:00-05:00",
    eventDateString: "December 11-12, 2026 • Medellín, Colombia",
    series: "Blockchain Week",
    geo: {
      country: "Colombia",
      continent: "South America",
    },
    features: ["speakers", "agenda"],
    eventType: "whitelabel",
    authAllyIds: ["hash-poker-room"],
    isDemo: false,
    branding: {
      primaryColor: "#FCD116",
      secondaryColor: "#050507",
      logo: "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/cbweek2026/branding/cbweek2026-logo.webp",
      favicon: "/favicon.ico",
    },
    api: {
      basePath: "/api/cbweek2026",
      endpoints: { ...BSL_SHARED_API_ENDPOINTS },
    },
    routes: {
      home: "/events/cbweek2026/home",
      speakers: "/events/cbweek2026/speakers",
      bookings: "/events/cbweek2026/my-bookings",
      admin: "/events/cbweek2026/admin",
    },
    // CBWeek has not announced a timed 2026 programme or confirmed speakers.
    // The following is a clearly labelled HashPass demo programme, created
    // from CBWeek's ten published topic pillars (2026-09-02), not an
    // organizer-announced schedule.
    speakers: [
      {
        id: "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6202",
        name: "Lucero Dextre",
        title: "COO",
        company: "LATAM Blockchain Events LLC",
        bio: "COO of LATAM Blockchain Events LLC. Listed on the official CBWeek contact section; included in this HashPass demo programme at organizer direction, not as an officially announced CBWeek 2026 speaker.",
        image: "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/cbweek2026/speakers/lucero-dextre.png",
        isActive: true,
      },
      {
        id: "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6201",
        name: "Bryan Aguilar",
        title: "CEO",
        company: "LATAM Blockchain Events LLC",
        bio: "CEO of LATAM Blockchain Events LLC. Listed on the official CBWeek contact section; included in this HashPass demo programme at organizer direction, not as an officially announced CBWeek 2026 speaker.",
        image: "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/cbweek2026/speakers/bryan-aguilar.png",
        isActive: true,
      },
      {
        id: "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6203",
        name: "Edward Calderón",
        title: "CEO",
        company: "HASHPASS",
        bio: "CEO of HashPass and blockchain technology leader. Included in this HashPass demo programme at organizer direction, not as an officially announced CBWeek 2026 speaker.",
        image: "https://hashpass-production-event-media-952191196420-us-east-2.s3.us-east-2.amazonaws.com/events/cbweek2026/speakers/edward-calderon.png",
        isActive: true,
      },
      ...CBWEEK2026_PAST_EDITION_SPEAKERS,
    ],
    dayThemes: {
      "1": {
        es: "Programa demo · Main Day basado en los temas oficiales",
        en: "Demo programme · Main Day based on official topics",
      },
    },
    agenda: [
      { id: "cbweek2026-demo-01", time: "2026-12-12T08:30:00-05:00", title: "Acreditación y bienvenida", description: "Programa demo de HashPass para el Main Day (08:30–18:00).", type: "registration", location: "Registro · Hotel InterContinental Medellín", day: "1" },
      { id: "cbweek2026-demo-02", time: "2026-12-12T09:00:00-05:00", title: "Apertura: Medellín entra al mapa cripto de LATAM", description: "Demo keynote de apertura del programa basado en los temas publicados por CBWeek.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6201"], type: "keynote", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-03", time: "2026-12-12T09:30:00-05:00", title: "Blockchain, Bitcoin, Criptomonedas & Trading", description: "Fundamentos, adopción y estrategias para entender y operar el ecosistema cripto global. Tema publicado por CBWeek; sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6201"], type: "keynote", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-04", time: "2026-12-12T10:00:00-05:00", title: "Forex, Inversiones & Mercados Financieros · Exchanges & Brokers", description: "Análisis macroeconómico, gestión de riesgo, oportunidades, plataformas, liquidez y herramientas que conectan a inversionistas con mercados globales. Sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6202", "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6201"], type: "panel", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-05", time: "2026-12-12T11:00:00-05:00", title: "Coffee break y visitas a stands", description: "Espacio demo para networking y descubrimiento de soluciones.", type: "break", location: "Zona de Stands", day: "1" },
      { id: "cbweek2026-demo-06", time: "2026-12-12T11:15:00-05:00", title: "Activos Digitales, Stablecoins, OTC, P2P, Liquidez, Wallets & Pagos Digitales", description: "Infraestructura y soluciones para custodiar, intercambiar y mover valor digital sin fronteras. Tema publicado por CBWeek; sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6202"], type: "panel", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-07", time: "2026-12-12T12:15:00-05:00", title: "Tokenización, RWA, Web3, Fintech & Startups", description: "Casos de innovación que llevan activos, productos y nuevos negocios al entorno on-chain. Tema publicado por CBWeek; sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6203"], type: "keynote", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-08", time: "2026-12-12T12:45:00-05:00", title: "Custodia, Servicios Institucionales & Soluciones B2B", description: "Servicios seguros y escalables para empresas e instituciones que adoptan activos digitales. Tema publicado por CBWeek; sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6201", "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6203"], type: "panel", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-09", time: "2026-12-12T13:45:00-05:00", title: "Almuerzo y networking", description: "Espacio demo de conexiones de negocio.", type: "meal", location: "Networking Zone", day: "1" },
      { id: "cbweek2026-demo-10", time: "2026-12-12T14:45:00-05:00", title: "DeFi, Regulación & Marco Legal LATAM", description: "Protocolos descentralizados y marcos normativos que están definiendo el futuro financiero regional. Tema publicado por CBWeek; sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6202", "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6203"], type: "panel", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-11", time: "2026-12-12T15:45:00-05:00", title: "Educación Financiera & Web3", description: "Conocimiento práctico para tomar mejores decisiones y participar responsablemente en la economía digital. Tema publicado por CBWeek; taller demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6202"], type: "workshop", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-12", time: "2026-12-12T16:15:00-05:00", title: "Inteligencia Artificial & Tecnologías Emergentes", description: "Aplicaciones de IA y tecnologías emergentes que transforman productos, operaciones y experiencias digitales. Tema publicado por CBWeek; taller demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6203"], type: "workshop", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-13", time: "2026-12-12T16:45:00-05:00", title: "Security, Compliance & Blockchain Analytics", description: "Prevención de fraude, trazabilidad y cumplimiento para construir un ecosistema Web3 más confiable. Tema publicado por CBWeek; sesión demo.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6203"], type: "keynote", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-14", time: "2026-12-12T17:15:00-05:00", title: "Cierre: conexiones que impulsan el circuito LATAM", description: "Panel demo de cierre sobre educación, adopción, negocios y experiencias presenciales en la región.", speakers: ["90e7014d-0d4b-4ee0-a7bf-b5f3b8db6201", "90e7014d-0d4b-4ee0-a7bf-b5f3b8db6202"], type: "keynote", location: "Main Stage", day: "1" },
      { id: "cbweek2026-demo-15", time: "2026-12-12T17:45:00-05:00", title: "Networking de cierre", description: "17:45–18:00 · Cierre del Main Day. Espacio demo de conexiones.", type: "break", location: "Networking Zone", day: "1" },
    ],
    quickAccessItems: [
      {
        id: "agenda",
        title: "Event Agenda",
        subtitle: "Demo programme · Dec 12",
        icon: "event",
        color: "#34A853",
        route: "/events/cbweek2026/agenda",
      },
      {
        id: "speakers",
        title: "Speakers",
        subtitle: "Demo speaker directory",
        icon: "people",
        color: "#087C80",
        route: "/events/cbweek2026/speakers/calendar",
      },
      {
        id: "event-info",
        title: "Event Information",
        subtitle: "Details & Logistics",
        icon: "info",
        color: "#FF9500",
        route: "/events/cbweek2026/event-info",
      },
    ],
  },
  default: {
    id: "default",
    name: "HASHPASS",
    domain: "hashpass.tech",
    title: "HASHPASS",
    subtitle: "Digital Identity & Wallet Platform",
    image: "/assets/images/hashpass-banner.jpg",
    color: "#6366f1",
    features: ["auth", "dashboard", "wallet"],
    eventType: "hashpass",
    branding: {
      primaryColor: "#6366f1",
      secondaryColor: "#8b5cf6",
      logo: "/assets/logos/hashpass/logo-full-hashpass-white.svg",
      favicon: "/favicon.ico",
    },
    api: {
      basePath: "/api",
      endpoints: { auth: "/api/auth", users: "/api/users" },
    },
    routes: {
      home: "/",
      speakers: "/(shared)/dashboard/explore",
      bookings: "/(shared)/dashboard/wallet",
    },
  },
} as const;

export type EventId = keyof typeof EVENTS;
