import React from 'react';
import {AbsoluteFill, Audio, Easing, Img, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {openProofContent as c} from '../../../../packages/config/src/openproof-content';
// start/dur (in frames @30fps) are derived from each scene's real narration
// clip length (see public/openproof/narration/en/*.mp3, generated by
// scripts/generate-openproof-narration.mjs) plus a trailing pause, not from
// the originally hand-guessed captions.srt timing — that guess undershot
// scene 1's actual spoken length by 6s. public/openproof/captions.srt and
// voiceover.md are kept in sync with these numbers; re-run the narration
// script and update both files together if any voiceover line changes.
const scenes=[
 {start:0,dur:210,kicker:'OPENPROOF',title:'Attendance should outlive the platform.',body:'A credential is only useful if it survives the platform that issued it.'},
 {start:210,dur:510,kicker:'THE SILO PROBLEM',title:'Today, attendance lives in silos.',body:'Private databases disconnect attendees, organizers and partners.'},
 {start:720,dur:330,kicker:'HASH PASS × ARKIV',title:'One shared attendance schema.',body:'Event · AttendanceClaim · CheckInReceipt · CrossAppAttestation'},
 {start:1050,dur:390,kicker:'ISSUANCE FLOW',title:'Verify. Issue. Transfer control.',body:'Organizer → QR check-in → HashPass verification → AttendanceClaim → attendee wallet'},
 {start:1440,dur:360,kicker:'ARKIV PRIMITIVES',title:'Queryable. Time-scoped. Owned.',body:'$creator proves the issuer. $owner proves who controls the credential.'},
 {start:1800,dur:330,kicker:'CROSS-APP VERIFICATION',title:'Verified attendance.',body:'Issuer verified · Credential active · No dependency on the HashPass private API'},
 {start:2130,dur:240,kicker:'PRIVACY BOUNDARY',title:'Personal data stays private.',body:'Arkiv stores only public proof hashes, pseudonymous IDs and credential metadata.'},
 {start:2370,dur:150,kicker:'OPENPROOF',title:'Portable attendance for every event.',body:'Attendance should outlive the platform.'},
] as const;
const MUSIC_VOLUME=0.12;
// Small gap so narration starts just after the title/card finish sliding in
// rather than talking over the entrance animation.
const NARRATION_DELAY_FRAMES=10;
export const OpenProof:React.FC=()=> <AbsoluteFill style={{background:'#050812',color:'#f7f9ff',fontFamily:'Arial, sans-serif'}}>
  <Audio src={staticFile('audio/music/elegant-bed.mp3')} volume={MUSIC_VOLUME}/>
  {scenes.map((s,i)=><Sequence key={s.title} from={s.start} durationInFrames={s.dur}><Scene index={i} {...s}/><Sequence from={NARRATION_DELAY_FRAMES}><Audio src={staticFile(`openproof/narration/en/${String(i+1).padStart(2,'0')}.mp3`)}/></Sequence></Sequence>)}
  <Watermark/>
</AbsoluteFill>;
function Watermark(){const f=useCurrentFrame();const enter=interpolate(f,[0,30],[0,1],{extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <div style={{position:'absolute',top:56,right:64,display:'flex',alignItems:'center',gap:16,opacity:enter*0.92}}><Img src={staticFile('brand/logo-full-hashpass-black.svg')} style={{height:28}}/><ArkivBadge/></div>}
function ArkivBadge({size='md'}:{size?:'sm'|'md'}){const big=size==='md';return <span style={{fontFamily:'monospace',fontSize:big?18:14,letterSpacing:3,display:'inline-flex',alignItems:'center',gap:big?7:5,padding:big?'7px 14px':'4px 9px',border:'1px solid #4dd8ff66',borderRadius:999,background:'#4dd8ff14',color:'#e8fbff',whiteSpace:'nowrap'}}><span style={{color:'#4dd8ff88'}}>[</span><b style={{color:'#4dd8ff',fontWeight:700}}>ARKIV</b><span style={{color:'#4dd8ff88'}}>]</span></span>}
function CheckBadge(){return <div style={{width:60,height:60,minWidth:60,borderRadius:'50%',border:'2px solid #68e0ad',display:'grid',placeItems:'center'}}><svg width="26" height="26" viewBox="0 0 24 24" fill="none"><path d="M4 12.5L9.5 18L20 6" stroke="#68e0ad" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg></div>}
function CredentialCard({progress}:{progress:number}){return <div style={{position:'relative',height:220,border:'1px solid #8b7cff55',borderRadius:22,background:'linear-gradient(135deg,#131627,#0a0d1a)',transform:`scale(${.96+.04*progress})`,opacity:progress,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 44px'}}><div style={{display:'flex',flexDirection:'column',gap:14}}><div style={{display:'flex',alignItems:'center',gap:16}}><Img src={staticFile('brand/logo-full-hashpass-black.svg')} style={{height:20}}/><ArkivBadge size="sm"/></div><div style={{fontFamily:'monospace',fontSize:27,color:'#68e0ad',letterSpacing:1}}>claim-chile-ana-001</div><div style={{fontFamily:'monospace',fontSize:16,color:'#8895a8'}}>$owner wallet:demo-ana &middot; VERIFIED &middot; 5 YEARS</div></div><CheckBadge/></div>}
// Plain, single-stroke line icons (24x24, currentColor) so every label card reads
// at a glance instead of relying on text alone. Keyed by the exact label string
// each scene passes in — an unrecognised label still renders (generic dot) rather
// than breaking the slide, since new labels will keep getting added over time.
const ICON_PATHS:Record<string,string>={
  platform:'M3 4h18v12H3zM8 20h8M12 16v4',
  event:'M3.5 5h17v15H3.5zM3.5 9.5h17M8 3v4M16 3v4',
  claim:'M12 3l7 3.2v5.3c0 4.6-3 8.3-7 9.5-4-1.2-7-4.9-7-9.5V6.2zM9 12l2.2 2.2L15.5 9.8',
  receipt:'M6 3h12v18l-2.5-1.6L13 21l-2.5-1.6L8 21l-2-1.6zM9 8h6M9 12h6',
  crossapp:'M3 3h8v8H3zM13 13h8v8h-8zM11 7h4a2 2 0 0 1 2 2v4',
  organizer:'M12 8a3.4 3.4 0 1 0 0-6.8 3.4 3.4 0 0 0 0 6.8zM5 20c0-3.6 3.1-6.4 7-6.4s7 2.8 7 6.4',
  qr:'M3.5 3.5h6v6h-6zM14.5 3.5h6v6h-6zM3.5 14.5h6v6h-6zM14.5 14.5h3v3h-3zM20.5 14.5v3M17.5 20.5h3',
  hash:'M9 3L7 21M17 3l-2 18M4 9h16M3.5 15h16',
  wallet:'M3.5 7.5A2.5 2.5 0 0 1 6 5h11a2 2 0 0 1 2 2v2M3.5 7.5h17v12h-17zM16.7 13.7h.01',
  search:'M10.5 17a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13zM20 20l-4.8-4.8',
  clock:'M12 20.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17zM12 7.5V12l3.2 2',
  creator:'M4 20l1-4.5L15.5 5a2 2 0 0 1 2.8 0l.7.7a2 2 0 0 1 0 2.8L8.5 19zM13.5 6.5l4 4',
  owner:'M8.5 13a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9zM11.8 11.8L20 20M15.5 15.5l2 2',
  campus:'M12 3l9 4.5-9 4.5-9-4.5zM6 10.5V16c0 1.5 2.7 3 6 3s6-1.5 6-3v-5.5',
  query:'M4 12h16M14 6l6 6-6 6',
  verified:'M12 20.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17zM8.2 12.3l2.4 2.4 5-5.2',
  private:'M5 10.5h14v9.5H5zM8 10.5V7.5a4 4 0 0 1 8 0v3',
  public:'M12 20.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17zM3.5 12h17M12 3.5c2.5 2.3 3.8 5.3 3.8 8.5s-1.3 6.2-3.8 8.5c-2.5-2.3-3.8-5.3-3.8-8.5S9.5 5.8 12 3.5z',
  dot:'M12 12h.01',
};
const ICON_BY_LABEL:Record<string,string>={
  'EVENT PLATFORM A':'platform','EVENT PLATFORM B':'platform','EVENT PLATFORM C':'platform',
  'Event':'event','AttendanceClaim':'claim','CheckInReceipt':'receipt','CrossAppAttestation':'crossapp',
  'ORGANIZER':'organizer','QR CHECK-IN':'qr','HASHPASS':'hash','CLAIM':'claim','WALLET':'wallet',
  'QUERYABLE':'search','TIME-SCOPED':'clock','$creator':'creator','$owner':'owner',
  'OPEN CAMPUS':'campus','→ ARKIV QUERY →':'query','✓ VERIFIED':'verified',
  'PRIVATE: names · emails · QR secrets':'private','PUBLIC: proof hash · issuer · expiry':'public',
};
function Icon({name,color,size=24}:{name:string;color:string;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={1.6} strokeLinecap="round" strokeLinejoin="round"><path d={ICON_PATHS[name]||ICON_PATHS.dot}/></svg>}
function IconBadge({label,color}:{label:string;color:string}){return <div style={{width:52,height:52,minWidth:52,borderRadius:'50%',border:`1px solid ${color}66`,background:`${color}14`,display:'grid',placeItems:'center'}}><Icon name={ICON_BY_LABEL[label]||'dot'} color={color}/></div>}
function Scene({index,dur,kicker,title,body}:{index:number;dur:number;kicker:string;title:string;body:string}){const f=useCurrentFrame();const enter=interpolate(f,[0,24],[0,1],{extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const fade=index===7?interpolate(f,[dur-25,dur],[1,0],{extrapolateLeft:'clamp'}):1;return <AbsoluteFill style={{opacity:fade,padding:'100px 120px',display:'flex',flexDirection:'column',justifyContent:'space-between',overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 80% 20%,#8b7cff20,transparent 38%),linear-gradient(#ffffff07 1px,transparent 1px),linear-gradient(90deg,#ffffff07 1px,transparent 1px)',backgroundSize:'auto,64px 64px,64px 64px'}}/><div style={{position:'relative',transform:`translateY(${(1-enter)*35}px)`,opacity:enter}}><div style={{fontFamily:'monospace',fontSize:22,letterSpacing:5,color:'#4dd8ff',marginBottom:42}}>{String(index+1).padStart(2,'0')} / {kicker}</div><div style={{fontSize:index===0||index===7?106:86,fontWeight:700,lineHeight:1.02,letterSpacing:-4,maxWidth:1450}}>{title}</div><div style={{fontSize:31,lineHeight:1.5,color:'#aeb9cb',maxWidth:1380,marginTop:38}}>{body}</div></div><Visual index={index} progress={enter}/><div style={{position:'relative',display:'flex',justifyContent:'space-between',alignItems:'end'}}><div style={{fontSize:24,color:'#d7deeb',background:'#0b1120e8',border:'1px solid #ffffff24',borderRadius:12,padding:'15px 22px',maxWidth:1500}}>{c.voiceover[index]}</div><div style={{display:'flex',alignItems:'center',gap:10}}><ArkivBadge size="sm"/><span style={{fontFamily:'monospace',fontSize:16,color:'#768399',letterSpacing:2}}>IDEATHON</span></div></div></AbsoluteFill>}
function Visual({index,progress}:{index:number;progress:number}){const labels:string[]=index===1?['EVENT PLATFORM A','EVENT PLATFORM B','EVENT PLATFORM C']:index===2?c.entities.map((x:{name:string})=>x.name):index===3?['ORGANIZER','QR CHECK-IN','HASHPASS','CLAIM','WALLET']:index===4?['QUERYABLE','TIME-SCOPED','$creator','$owner']:index===5?['OPEN CAMPUS','→ ARKIV QUERY →','✓ VERIFIED']:index===6?['PRIVATE: names · emails · QR secrets','PUBLIC: proof hash · issuer · expiry']:[];if(!labels.length)return <CredentialCard progress={progress}/>;return <div style={{position:'relative',display:'flex',gap:18,alignItems:'stretch',height:220}}>{labels.map((x,i)=>{const color=i%2?'#8b7cff':'#4dd8ff';return <div key={x} style={{flex:1,border:`1px solid ${color}77`,borderRadius:18,background:'#0b1220',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:14,textAlign:'center',padding:22,transform:`translateY(${(1-progress)*(20+i*7)}px)`,opacity:progress}}><IconBadge label={x} color={color}/><span style={{fontFamily:'monospace',fontSize:21}}>{x}</span></div>})}</div>}
