import React from 'react';
import {AbsoluteFill, Audio, Easing, Img, interpolate, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {openProofContent as c} from '../../../../packages/config/src/openproof-content';
// start/dur (in frames @30fps) are derived from each scene's real narration
// clip length (see public/openproof/narration/en/*.mp3, generated by
// scripts/generate-openproof-narration.mjs) plus a trailing pause, not from
// the originally hand-guessed captions.srt timing — that guess undershot
// scene 1's actual spoken length by 6s. public/openproof/captions.srt and
// voiceover.md are kept in sync with these numbers; re-run the narration
// script and update both files together if any voiceover line changes.
const scenes=[
 {start:0,dur:210,kicker:'OPENPROOF',title:'Attendance should outlive the platform.',body:'A credential is only useful if it survives the platform that issued it.'},
 {start:210,dur:510,kicker:'THE SILO PROBLEM',title:'Today, attendance lives in silos.',body:'Private databases disconnect attendees, organizers and partners.'},
 {start:720,dur:330,kicker:'HASH PASS × ARKIV',title:'One shared attendance schema.',body:'Event · AttendanceClaim · CheckInReceipt · CrossAppAttestation'},
 {start:1050,dur:390,kicker:'ISSUANCE FLOW',title:'Verify. Issue. Transfer control.',body:'Organizer → QR check-in → HashPass verification → AttendanceClaim → attendee wallet'},
 {start:1440,dur:360,kicker:'ARKIV PRIMITIVES',title:'Queryable. Time-scoped. Owned.',body:'$creator proves the issuer. $owner proves who controls the credential.'},
 {start:1800,dur:330,kicker:'CROSS-APP VERIFICATION',title:'Verified attendance.',body:'Issuer verified · Credential active · No dependency on the HashPass private API'},
 {start:2130,dur:240,kicker:'PRIVACY BOUNDARY',title:'Personal data stays private.',body:'Arkiv stores only public proof hashes, pseudonymous IDs and credential metadata.'},
 {start:2370,dur:150,kicker:'OPENPROOF',title:'Portable attendance for every event.',body:'Attendance should outlive the platform.'},
] as const;
const MUSIC_VOLUME=0.12;
// Small gap so narration starts just after the title/card finish sliding in
// rather than talking over the entrance animation.
const NARRATION_DELAY_FRAMES=10;
export const OpenProof:React.FC=()=> <AbsoluteFill style={{background:'#050812',color:'#f7f9ff',fontFamily:'Arial, sans-serif'}}>
  <Audio src={staticFile('audio/music/elegant-bed.mp3')} volume={MUSIC_VOLUME}/>
  {scenes.map((s,i)=><Sequence key={s.title} from={s.start} durationInFrames={s.dur}><Scene index={i} {...s}/><Sequence from={NARRATION_DELAY_FRAMES}><Audio src={staticFile(`openproof/narration/en/${String(i+1).padStart(2,'0')}.mp3`)}/></Sequence></Sequence>)}
  <Watermark/>
</AbsoluteFill>;
function Watermark(){const f=useCurrentFrame();const enter=interpolate(f,[0,30],[0,1],{extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <div style={{position:'absolute',top:56,right:64,display:'flex',alignItems:'center',gap:16,opacity:enter*0.92}}><Img src={staticFile('brand/logo-full-hashpass-black.svg')} style={{height:28}}/><ArkivBadge/></div>}
function ArkivBadge({size='md'}:{size?:'sm'|'md'}){const big=size==='md';return <span style={{fontFamily:'monospace',fontSize:big?18:14,letterSpacing:3,display:'inline-flex',alignItems:'center',gap:big?7:5,padding:big?'7px 14px':'4px 9px',border:'1px solid #4dd8ff66',borderRadius:999,background:'#4dd8ff14',color:'#e8fbff',whiteSpace:'nowrap'}}><span style={{color:'#4dd8ff88'}}>[</span><b style={{color:'#4dd8ff',fontWeight:700}}>ARKIV</b><span style={{color:'#4dd8ff88'}}>]</span></span>}
// ---------------------------------------------------------------------------
// Animation helpers. Everything below uses only core `remotion` primitives
// (spring/interpolate) plus native SVG stroke-dash drawing — deliberately no
// extra animation dependency, so nothing can drift from the pinned Remotion
// version and the render stays reproducible on the CI runner.
// ---------------------------------------------------------------------------

// Spring entrance, optionally delayed so a row of items can stagger in.
function useEnter(delay=0,damping=14){
  const f=useCurrentFrame();
  const {fps}=useVideoConfig();
  return spring({frame:f-delay,fps,config:{damping,mass:0.6,stiffness:120}});
}

// A stroke that draws itself. pathLength=1 normalises any `d` to a 0..1 length
// so one dash of length 1 with a shrinking offset reveals it left-to-right,
// regardless of the path's real geometry.
function DrawPath({d,color,width=1.6,draw}:{d:string;color:string;width?:number;draw:number}){
  return <path d={d} stroke={color} strokeWidth={width} strokeLinecap="round" strokeLinejoin="round" fill="none"
    pathLength={1} strokeDasharray={1} strokeDashoffset={1-draw}/>;
}

function CheckBadge({delay=0}:{delay?:number}){
  const f=useCurrentFrame();
  const pop=useEnter(delay,11);
  const draw=interpolate(f-delay-8,[0,16],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  const halo=0.5+0.5*Math.sin((f-delay)/16);
  return <div style={{position:'relative',width:60,height:60,minWidth:60,display:'grid',placeItems:'center',transform:`scale(${pop})`}}>
    <div style={{position:'absolute',inset:0,borderRadius:'50%',border:'2px solid #68e0ad',opacity:0.9}}/>
    <div style={{position:'absolute',inset:-6,borderRadius:'50%',border:'1px solid #68e0ad',opacity:0.18*halo,transform:`scale(${1+0.08*halo})`}}/>
    <svg width="26" height="26" viewBox="0 0 24 24"><DrawPath d="M4 12.5L9.5 18L20 6" color="#68e0ad" width={3} draw={draw}/></svg>
  </div>;
}

function CredentialCard({progress}:{progress:number}){
  const f=useCurrentFrame();
  // Slow specular sweep so the hero/outro card keeps a little life after its
  // entrance settles, instead of freezing for the rest of the scene.
  const sweep=((f%150)/150)*260-60;
  return <div style={{position:'relative',height:220,border:'1px solid #8b7cff55',borderRadius:22,background:'linear-gradient(135deg,#131627,#0a0d1a)',transform:`scale(${.96+.04*progress})`,opacity:progress,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 44px',overflow:'hidden'}}>
    <div style={{position:'absolute',top:0,bottom:0,left:`${sweep}%`,width:'22%',background:'linear-gradient(90deg,transparent,#8b7cff1c,transparent)',pointerEvents:'none'}}/>
    <div style={{position:'relative',display:'flex',flexDirection:'column',gap:14}}>
      <div style={{display:'flex',alignItems:'center',gap:16}}><Img src={staticFile('brand/logo-full-hashpass-black.svg')} style={{height:20}}/><ArkivBadge size="sm"/></div>
      <div style={{fontFamily:'monospace',fontSize:27,color:'#68e0ad',letterSpacing:1}}>claim-chile-ana-001</div>
      <div style={{fontFamily:'monospace',fontSize:16,color:'#8895a8'}}>$owner wallet:demo-ana &middot; VERIFIED &middot; 5 YEARS</div>
    </div>
    <CheckBadge delay={14}/>
  </div>;
}
// Plain, single-stroke line icons (24x24, currentColor) so every label card reads
// at a glance instead of relying on text alone. Keyed by the exact label string
// each scene passes in — an unrecognised label still renders (generic dot) rather
// than breaking the slide, since new labels will keep getting added over time.
const ICON_PATHS:Record<string,string>={
  platform:'M3 4h18v12H3zM8 20h8M12 16v4',
  event:'M3.5 5h17v15H3.5zM3.5 9.5h17M8 3v4M16 3v4',
  claim:'M12 3l7 3.2v5.3c0 4.6-3 8.3-7 9.5-4-1.2-7-4.9-7-9.5V6.2zM9 12l2.2 2.2L15.5 9.8',
  receipt:'M6 3h12v18l-2.5-1.6L13 21l-2.5-1.6L8 21l-2-1.6zM9 8h6M9 12h6',
  crossapp:'M3 3h8v8H3zM13 13h8v8h-8zM11 7h4a2 2 0 0 1 2 2v4',
  organizer:'M12 8a3.4 3.4 0 1 0 0-6.8 3.4 3.4 0 0 0 0 6.8zM5 20c0-3.6 3.1-6.4 7-6.4s7 2.8 7 6.4',
  qr:'M3.5 3.5h6v6h-6zM14.5 3.5h6v6h-6zM3.5 14.5h6v6h-6zM14.5 14.5h3v3h-3zM20.5 14.5v3M17.5 20.5h3',
  hash:'M9 3L7 21M17 3l-2 18M4 9h16M3.5 15h16',
  wallet:'M3.5 7.5A2.5 2.5 0 0 1 6 5h11a2 2 0 0 1 2 2v2M3.5 7.5h17v12h-17zM16.7 13.7h.01',
  search:'M10.5 17a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13zM20 20l-4.8-4.8',
  clock:'M12 20.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17zM12 7.5V12l3.2 2',
  creator:'M4 20l1-4.5L15.5 5a2 2 0 0 1 2.8 0l.7.7a2 2 0 0 1 0 2.8L8.5 19zM13.5 6.5l4 4',
  owner:'M8.5 13a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9zM11.8 11.8L20 20M15.5 15.5l2 2',
  campus:'M12 3l9 4.5-9 4.5-9-4.5zM6 10.5V16c0 1.5 2.7 3 6 3s6-1.5 6-3v-5.5',
  query:'M4 12h16M14 6l6 6-6 6',
  verified:'M12 20.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17zM8.2 12.3l2.4 2.4 5-5.2',
  private:'M5 10.5h14v9.5H5zM8 10.5V7.5a4 4 0 0 1 8 0v3',
  public:'M12 20.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17zM3.5 12h17M12 3.5c2.5 2.3 3.8 5.3 3.8 8.5s-1.3 6.2-3.8 8.5c-2.5-2.3-3.8-5.3-3.8-8.5S9.5 5.8 12 3.5z',
  dot:'M12 12h.01',
};
const ICON_BY_LABEL:Record<string,string>={
  'EVENT PLATFORM A':'platform','EVENT PLATFORM B':'platform','EVENT PLATFORM C':'platform',
  'Event':'event','AttendanceClaim':'claim','CheckInReceipt':'receipt','CrossAppAttestation':'crossapp',
  'ORGANIZER':'organizer','QR CHECK-IN':'qr','HASHPASS':'hash','CLAIM':'claim','WALLET':'wallet',
  'QUERYABLE':'search','TIME-SCOPED':'clock','$creator':'creator','$owner':'owner',
  'OPEN CAMPUS':'campus','→ ARKIV QUERY →':'query','✓ VERIFIED':'verified',
  'PRIVATE: names · emails · QR secrets':'private','PUBLIC: proof hash · issuer · expiry':'public',
};
// Icons draw themselves in rather than popping, which reads as "being issued /
// being built" — the thing the video is actually describing.
function Icon({name,color,size=24,draw=1}:{name:string;color:string;size?:number;draw?:number}){
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
    <DrawPath d={ICON_PATHS[name]||ICON_PATHS.dot} color={color} draw={draw}/>
  </svg>;
}

function IconBadge({label,color,delay=0}:{label:string;color:string;delay?:number}){
  const f=useCurrentFrame();
  const pop=useEnter(delay,12);
  const draw=interpolate(f-delay-5,[0,20],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  const halo=0.5+0.5*Math.sin((f-delay)/20);
  return <div style={{position:'relative',width:52,height:52,minWidth:52,display:'grid',placeItems:'center',transform:`scale(${pop})`}}>
    <div style={{position:'absolute',inset:0,borderRadius:'50%',border:`1px solid ${color}66`,background:`${color}14`}}/>
    <div style={{position:'absolute',inset:-5,borderRadius:'50%',border:`1px solid ${color}`,opacity:0.16*halo,transform:`scale(${1+0.07*halo})`}}/>
    <Icon name={ICON_BY_LABEL[label]||'dot'} color={color} draw={draw}/>
  </div>;
}

// Connector between two flow steps: the line draws in, then a pulse travels
// along it on a loop — showing the credential actually moving through the
// pipeline instead of five disconnected cards sitting side by side.
function Connector({color,delay}:{color:string;delay:number}){
  const f=useCurrentFrame();
  const draw=interpolate(f-delay,[0,16],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  const since=f-delay-16;
  const t=since>0?(since%42)/42:0;
  return <svg width={46} height={26} viewBox="0 0 46 26" style={{flexShrink:0,alignSelf:'center'}}>
    <DrawPath d="M3 13H36" color={color} width={2} draw={draw}/>
    <g opacity={draw}><DrawPath d="M31 8L36 13L31 18" color={color} width={2} draw={draw}/></g>
    {since>0&&<circle cx={3+33*t} cy={13} r={3.4} fill={color} opacity={Math.sin(t*Math.PI)}/>}
  </svg>;
}

// Only scenes that describe an actual sequence get connectors. The silo scene
// (1) deliberately has none — disconnection is its whole point — and the
// schema/primitives scenes are lists, not pipelines.
const FLOW_SCENES=new Set([3,5]);
function Scene({index,dur,kicker,title,body}:{index:number;dur:number;kicker:string;title:string;body:string}){
  const f=useCurrentFrame();
  const enter=useEnter(0,16);
  const kickerIn=useEnter(0,18);
  const bodyIn=useEnter(8,18);
  const capIn=useEnter(14,18);
  const fade=index===7?interpolate(f,[dur-25,dur],[1,0],{extrapolateLeft:'clamp'}):1;
  // Very slow parallax on the backdrop so long scenes keep a sense of motion.
  const drift=interpolate(f,[0,dur],[0,-18]);
  return <AbsoluteFill style={{opacity:fade,padding:'100px 120px',display:'flex',flexDirection:'column',justifyContent:'space-between',overflow:'hidden'}}>
    <div style={{position:'absolute',inset:-40,transform:`translateY(${drift}px)`,background:'radial-gradient(circle at 80% 20%,#8b7cff20,transparent 38%),linear-gradient(#ffffff07 1px,transparent 1px),linear-gradient(90deg,#ffffff07 1px,transparent 1px)',backgroundSize:'auto,64px 64px,64px 64px'}}/>
    <div style={{position:'relative'}}>
      <div style={{fontFamily:'monospace',fontSize:22,letterSpacing:5,color:'#4dd8ff',marginBottom:42,opacity:kickerIn,transform:`translateX(${(1-kickerIn)*-18}px)`}}>{String(index+1).padStart(2,'0')} / {kicker}</div>
      <div style={{fontSize:index===0||index===7?106:86,fontWeight:700,lineHeight:1.02,letterSpacing:-4,maxWidth:1450,opacity:enter,transform:`translateY(${(1-enter)*34}px)`}}>{title}</div>
      <div style={{fontSize:31,lineHeight:1.5,color:'#aeb9cb',maxWidth:1380,marginTop:38,opacity:bodyIn,transform:`translateY(${(1-bodyIn)*20}px)`}}>{body}</div>
    </div>
    <Visual index={index} progress={enter}/>
    <div style={{position:'relative',display:'flex',justifyContent:'space-between',alignItems:'end',opacity:capIn,transform:`translateY(${(1-capIn)*14}px)`}}>
      <div style={{fontSize:24,color:'#d7deeb',background:'#0b1120e8',border:'1px solid #ffffff24',borderRadius:12,padding:'15px 22px',maxWidth:1500}}>{c.voiceover[index]}</div>
      <div style={{display:'flex',alignItems:'center',gap:10}}><ArkivBadge size="sm"/><span style={{fontFamily:'monospace',fontSize:16,color:'#768399',letterSpacing:2}}>IDEATHON</span></div>
    </div>
  </AbsoluteFill>;
}
// One card in a row: springs up, staggered behind its neighbours, and keeps a
// faint breathing glow so a held scene never looks like a frozen screenshot.
function VisualCard({label,color,delay,emphasis}:{label:string;color:string;delay:number;emphasis?:boolean}){
  const f=useCurrentFrame();
  const enter=useEnter(delay);
  const glow=0.5+0.5*Math.sin((f-delay)/26);
  return <div style={{
    flex:1,minWidth:0,border:`1px solid ${color}${emphasis?'':'77'}`,borderRadius:18,
    background:emphasis?`linear-gradient(160deg,${color}1f,#0b1220)`:'#0b1220',
    boxShadow:emphasis?`0 0 ${18+14*glow}px ${color}2e`:'none',
    display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:14,
    textAlign:'center',padding:22,
    transform:`translateY(${(1-enter)*26}px) scale(${0.97+0.03*enter})`,opacity:enter,
  }}>
    <IconBadge label={label} color={color} delay={delay+3}/>
    <span style={{fontFamily:'monospace',fontSize:20,lineHeight:1.35}}>{label}</span>
  </div>;
}

function Visual({index}:{index:number;progress:number}){
  const labels:string[]=index===1?['EVENT PLATFORM A','EVENT PLATFORM B','EVENT PLATFORM C']
    :index===2?c.entities.map((x:{name:string})=>x.name)
    :index===3?['ORGANIZER','QR CHECK-IN','HASHPASS','CLAIM','WALLET']
    :index===4?['QUERYABLE','TIME-SCOPED','$creator','$owner']
    :index===5?['OPEN CAMPUS','→ ARKIV QUERY →','✓ VERIFIED']
    :index===6?['PRIVATE: names · emails · QR secrets','PUBLIC: proof hash · issuer · expiry']:[];
  if(!labels.length)return <CredentialCard progress={1}/>;
  const isFlow=FLOW_SCENES.has(index);
  const isPrivacy=index===6;
  return <div style={{position:'relative',display:'flex',gap:isFlow?0:18,alignItems:'stretch',height:220}}>
    {labels.map((x,i)=>{
      // Privacy scene reads private-vs-public, not a rainbow: amber = withheld,
      // cyan = publicly verifiable.
      const color=isPrivacy?(i===0?'#f4bd68':'#4dd8ff'):i%2?'#8b7cff':'#4dd8ff';
      const delay=i*7;
      return <React.Fragment key={x}>
        {isFlow&&i>0&&<Connector color="#5c6b86" delay={delay-2}/>}
        {isPrivacy&&i>0&&<PrivacyBoundary delay={delay}/>}
        <VisualCard label={x} color={color} delay={delay} emphasis={isFlow&&i===labels.length-1}/>
      </React.Fragment>;
    })}
  </div>;
}

// The privacy scene's divider: a dashed wall that draws down between the two
// panels, making "boundary" a thing you see rather than a word in the caption.
function PrivacyBoundary({delay}:{delay:number}){
  const f=useCurrentFrame();
  const draw=interpolate(f-delay,[0,22],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  return <svg width={40} height={220} viewBox="0 0 40 220" style={{flexShrink:0}}>
    {/* No pathLength here on purpose: it would renormalise the 7/9 dash
        pattern to the path's 0..1 length and render as one solid line. The
        wipe comes from clipPath instead, so the dashes stay real. */}
    <path d="M20 6V214" stroke="#8895a8" strokeWidth={2} strokeDasharray="7 9" fill="none"
      opacity={0.75} style={{clipPath:`inset(0 0 ${(1-draw)*100}% 0)`}}/>
  </svg>;
}
