import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import seedPack from '../data/guatape.json';
import { buildItinerary, searchPlaces } from './engine';
import { getPack, getSavedItinerary, saveItinerary, savePack } from './storage';
import type { DestinationPack, ItineraryItem, Language } from './types';
import './styles.css';

const fallback=seedPack as DestinationPack;
type View='guide'|'businesses'|'essential';
const copy={en:{eyebrow:'OFFLINE DESTINATION INTELLIGENCE',title:'Guatapé, in your pocket.',subtitle:'Download local knowledge once. Explore confidently—even when your signal disappears.',download:'Download for offline use',ready:'Offline pack ready',ask:'What do you want to do in Guatapé?',placeholder:'I have 3 hours, COP 100,000. I like nature and local food.',plan:'Build my offline plan',local:'Support local',essential:'Essential',guide:'Ask LocalPass',businesses:'Local businesses',saved:'Saved offline',demo:'Simulate offline',online:'Online',offline:'Offline',why:'Why this fits',cost:'Estimated cost',time:'Time',empty:'Your practical plan will appear here.',dataset:'Demo dataset based on publicly available local information.',core:'Core guidance is running entirely on this device.'},es:{eyebrow:'INTELIGENCIA LOCAL SIN CONEXIÓN',title:'Guatapé, en tu bolsillo.',subtitle:'Descarga el conocimiento local una vez. Explora con confianza, incluso sin señal.',download:'Descargar para usar sin conexión',ready:'Paquete sin conexión listo',ask:'¿Qué quieres hacer en Guatapé?',placeholder:'Tengo 3 horas y COP 100.000. Me gusta la naturaleza y la comida local.',plan:'Crear mi plan sin conexión',local:'Apoya local',essential:'Esencial',guide:'Pregunta a LocalPass',businesses:'Negocios locales',saved:'Guardado sin conexión',demo:'Simular sin conexión',online:'En línea',offline:'Sin conexión',why:'Por qué encaja',cost:'Costo estimado',time:'Tiempo',empty:'Tu plan práctico aparecerá aquí.',dataset:'Datos de demostración basados en información local disponible públicamente.',core:'La guía esencial funciona completamente en este dispositivo.'}};

function App(){const [language,setLanguage]=useState<Language>('en');const [pack,setPack]=useState<DestinationPack>(fallback);const [downloaded,setDownloaded]=useState(false);const [simulated,setSimulated]=useState(false);const [online,setOnline]=useState(navigator.onLine);const [view,setView]=useState<View>('guide');const [query,setQuery]=useState('I have 3 hours, COP 100,000. I like nature and local food.');const [items,setItems]=useState<ItineraryItem[]>(getSavedItinerary);const t=copy[language];const offline=simulated||!online;
useEffect(()=>{getPack().then(p=>{if(p){setPack(p);setDownloaded(true)}});const on=()=>setOnline(navigator.onLine);addEventListener('online',on);addEventListener('offline',on);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[]);
const size=useMemo(()=>(new Blob([JSON.stringify(pack)]).size/1024).toFixed(0),[pack]);
async function download(){await savePack(fallback);setPack(fallback);setDownloaded(true);}
function plan(){const next=buildItinerary(pack,query,language);setItems(next);saveItinerary(next);}
return <><header><a className="brand" href="#top"><span className="mark">L</span>LocalPass <small>AI</small></a><div className="header-actions"><button className="lang" onClick={()=>setLanguage(language==='en'?'es':'en')} aria-label="Change language">{language.toUpperCase()}</button><span className={`status ${offline?'is-offline':''}`}><i/>{offline?t.offline:t.online}</span></div></header>
<main id="top"><section className="hero"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.subtitle}</p><div className="pack"><div className="pack-icon">↓</div><div><strong>Guatapé</strong><span>{downloaded?t.ready:`Offline pack · ${size} KB`}</span></div><button onClick={download} disabled={downloaded}>{downloaded?'✓ '+t.ready:t.download}</button></div></div><div className="hero-art" aria-label="Illustration of Guatapé"><div className="sun"/><div className="mountain m1"/><div className="mountain m2"/><div className="water"/><div className="town">▰ ▰ ▰ ▰</div><div className="art-label"><span>06°14′N</span><strong>Antioquia</strong></div></div></section>
<section className="offline-bar"><div><span className={`signal ${offline?'off':''}`}>◉</span><strong>{offline?t.offline:t.online}</strong><small>{offline?t.core:'Cloud enrichment available · Offline pack remains ready'}</small></div><label className="toggle"><input type="checkbox" checked={simulated} onChange={e=>setSimulated(e.target.checked)}/><span/>{t.demo}</label></section>
<nav><button className={view==='guide'?'active':''} onClick={()=>setView('guide')}>✦ {t.guide}</button><button className={view==='businesses'?'active':''} onClick={()=>setView('businesses')}>⌂ {t.businesses}</button><button className={view==='essential'?'active':''} onClick={()=>setView('essential')}>+ {t.essential}</button></nav>
{view==='guide'&&<section className="workspace"><div className="ask"><span className="section-no">01</span><h2>{t.ask}</h2><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.placeholder}/><div className="suggestions">{[language==='en'?'2 hours · COP 50,000':'2 horas · COP 50.000',language==='en'?'Local food':'Comida local',language==='en'?'Rainy day':'Día lluvioso'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div><button className="primary" onClick={plan}>✦ {t.plan}</button><p className="privacy">⌁ {offline?t.core:'Online planning may enrich results; place data stays local.'}</p></div><div className="results"><div className="result-title"><div><span className="section-no">02</span><h2>{language==='en'?'Your day, locally made':'Tu día, hecho localmente'}</h2></div>{items.length>0&&<span className="saved">✓ {t.saved}</span>}</div>{items.length===0?<div className="empty">✦<p>{t.empty}</p></div>:<div className="timeline">{items.map(item=>{const p=pack.places.find(x=>x.id===item.place_id)!;return <article key={item.place_id}><time>{item.start_time}</time><div><div className="card-head"><h3>{p.name}</h3>{p.local_business&&<span className="local">♥ {t.local}</span>}</div><p>{p[`description_${language}`]}</p><dl><div><dt>{t.time}</dt><dd>{item.duration} min</dd></div><div><dt>{t.cost}</dt><dd>COP {item.estimated_cost.toLocaleString()}</dd></div><div><dt>Internet</dt><dd>{language==='en'?'Not required':'No requerido'}</dd></div></dl><p className="reason"><b>{t.why}:</b> {item.reason}</p></div></article>})}</div>}</div></section>}
{view==='businesses'&&<section className="directory"><span className="section-no">02</span><h2>{t.businesses}</h2><p>{t.dataset}</p><div className="grid">{pack.places.filter(p=>p.local_business).map(p=><article key={p.id}><span className="local">♥ {t.local}</span><p className="category">{p.category}</p><h3>{p.name}</h3><p>{p[`description_${language}`]}</p><small>{p.location} · {p.opening_hours}</small><strong>COP {p.estimated_cost.toLocaleString()} · {p.accepted_payments.join(' / ')}</strong></article>)}</div></section>}
{view==='essential'&&<section className="directory"><span className="section-no">03</span><h2>{language==='en'?'Essential information':'Información esencial'}</h2><p>{t.core}</p><div className="essential-grid">{pack.essential.sort((a,b)=>a.priority-b.priority).map(e=><article key={e.type}><span>{e.type==='emergency'?'SOS':'i'}</span><div><h3>{e[`title_${language}`]}</h3><p>{e[`content_${language}`]}</p></div></article>)}</div></section>}
</main><footer><strong>LocalPass AI</strong><span>Download intelligence once. Use it many times.</span><span>Guatapé pilot · {pack.places.filter(p=>p.local_business).length} local operators · EN / ES</span></footer></>}
createRoot(document.getElementById('root')!).render(<App/>);
